// Catalogue expansion — MOBILE PHONES, TABLETS & MOBILE ACCESSORIES.
// Format: [categorySlug, brandName, name, priceGHS, opts]
//   opts.sale  = explicit sale price | "auto" | omitted
//   opts.v     = explicit variants [{ n, o, d }]
//   opts.sizes / opts.colors / opts.eu = generate variants
//   opts.new   = featured / recent arrival
//   opts.specs = short spec bullets used in the description
// Real products researched from Ghanaian retail (Jumia GH, Melcom,
// Telefonika, CompuGhana, official distributor catalogues).

export const PRODUCTS = [
  // ============ Smartphones ============
  ["smartphones", "Samsung", "Samsung Galaxy A06 64GB 3GB RAM Dual SIM", 749, { v: [{ n: "64GB / 3GB RAM", o: { Storage: "64GB", RAM: "3GB" }, d: 0 }, { n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 150 }], specs: ["6.7\" HD+ display", "50MP + 2MP dual camera", "5000mAh battery", "4G dual SIM"] }],
  ["smartphones", "Samsung", "Samsung Galaxy A05s 128GB 6GB RAM Dual SIM", 999, { sale: 949, v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.7\" FHD+ display", "50MP triple camera", "5000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy A16 5G 256GB 8GB RAM", 1399, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" Super AMOLED 90Hz", "50MP + 5MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy A26 5G 128GB 8GB RAM", 1549, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" Super AMOLED 120Hz", "50MP OIS camera", "5000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy A36 5G 128GB 8GB RAM", 1999, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 350 }], specs: ["6.7\" Super AMOLED 120Hz", "50MP OIS main camera", "5000mAh 45W charging"] }],
  ["smartphones", "Samsung", "Samsung Galaxy A56 5G 256GB 8GB RAM", 2899, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" Super AMOLED 120Hz", "50MP + 12MP + 5MP camera", "5000mAh 45W charging"] }],
  ["smartphones", "Samsung", "Samsung Galaxy M35 5G 128GB 6GB RAM", 1599, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 300 }], specs: ["6.6\" Super AMOLED 120Hz", "50MP triple camera", "6000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy F15 5G 128GB 6GB RAM", 1249, { sale: 1199, v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.6\" Super AMOLED 90Hz", "50MP triple camera", "6000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy S24 FE 128GB 8GB RAM", 3499, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 400 }], specs: ["6.7\" Dynamic AMOLED 2X 120Hz", "50MP triple camera", "4700mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy S25 5G 256GB 12GB RAM", 7499, { v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }, { n: "512GB / 12GB RAM", o: { Storage: "512GB", RAM: "12GB" }, d: 800 }], specs: ["6.3\" Dynamic AMOLED 2X 120Hz", "50MP + 12MP + 10MP camera", "4000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy S25 Ultra 5G 512GB 12GB RAM", 10499, { v: [{ n: "512GB / 12GB RAM", o: { Storage: "512GB", RAM: "12GB" }, d: 0 }], specs: ["6.9\" Dynamic AMOLED 2X 120Hz", "200MP quad camera", "5000mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy Z Flip5 5G 256GB 8GB RAM", 5499, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" Foldable AMOLED", "12MP dual camera", "3700mAh battery"] }],
  ["smartphones", "Samsung", "Samsung Galaxy Z Fold5 5G 256GB 12GB RAM", 10499, { sale: "auto", v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["7.6\" Foldable AMOLED 120Hz", "50MP triple camera", "4400mAh battery"] }],
  ["smartphones", "Apple", "Apple iPhone 12 mini 64GB", 5499, { sale: "auto", v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }, { n: "128GB", o: { Storage: "128GB" }, d: 400 }], specs: ["5.4\" Super Retina XDR", "Dual 12MP camera", "A14 Bionic chip"] }],
  ["smartphones", "Apple", "Apple iPhone 13 mini 128GB", 6499, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 500 }], specs: ["5.4\" Super Retina XDR", "Dual 12MP camera", "A15 Bionic chip"] }],
  ["smartphones", "Apple", "Apple iPhone 14 Plus 128GB", 9499, { sale: "auto", v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 700 }], specs: ["6.7\" Super Retina XDR", "Dual 12MP camera", "A15 Bionic chip"] }],
  ["smartphones", "Apple", "Apple iPhone 15 Plus 128GB", 11500, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 700 }], specs: ["6.7\" Super Retina XDR", "48MP + 12MP camera", "A16 Bionic chip"] }],
  ["smartphones", "Apple", "Apple iPhone 15 Pro Max 256GB", 18999, { sale: "auto", v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.7\" Super Retina XDR ProMotion", "48MP triple camera", "A17 Pro chip"] }],
  ["smartphones", "Apple", "Apple iPhone 16 128GB", 14500, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 800 }], specs: ["6.1\" Super Retina XDR", "48MP dual camera", "A18 chip"] }],
  ["smartphones", "Apple", "Apple iPhone 16 Pro 256GB", 19999, { sale: "auto", v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.3\" Super Retina XDR ProMotion", "48MP triple camera", "A18 Pro chip"] }],
  ["smartphones", "Apple", "Apple iPhone 16 Pro Max 512GB", 23999, { v: [{ n: "512GB", o: { Storage: "512GB" }, d: 0 }], specs: ["6.9\" Super Retina XDR ProMotion", "48MP triple camera", "A18 Pro chip"] }],
  ["smartphones", "Tecno", "Tecno Spark Go 2025 64GB 4GB RAM", 649, { sale: 599, v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.6\" HD+ 90Hz display", "16MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "Tecno", "Tecno Spark 30C 128GB 4GB RAM", 849, { v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }, { n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 200 }], specs: ["6.67\" HD+ 120Hz display", "50MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Tecno", "Tecno Spark 30 Pro 256GB 8GB RAM", 1149, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" FHD+ 120Hz display", "108MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Tecno", "Tecno Camon 30 5G 256GB 8GB RAM", 1649, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" AMOLED 120Hz", "50MP OIS camera", "5000mAh 70W charging"] }],
  ["smartphones", "Tecno", "Tecno Camon 30s Pro 256GB 12GB RAM", 1599, { sale: "auto", v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.78\" AMOLED 120Hz", "50MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "Tecno", "Tecno Camon 40 5G 256GB 8GB RAM", 1799, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" FHD+ 120Hz", "50MP OIS main camera", "5000mAh 45W charging"] }],
  ["smartphones", "Tecno", "Tecno Pova 6 Neo 256GB 8GB RAM", 1149, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" FHD+ 120Hz", "50MP dual camera", "6000mAh 33W charging"] }],
  ["smartphones", "Tecno", "Tecno Phantom V Flip2 5G 256GB 8GB RAM", 3999, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.9\" foldable LTPO AMOLED", "50MP dual camera", "4720mAh battery"] }],
  ["smartphones", "Infinix", "Infinix Smart 9 64GB 3GB RAM", 699, { sale: 649, v: [{ n: "64GB / 3GB RAM", o: { Storage: "64GB", RAM: "3GB" }, d: 0 }], specs: ["6.7\" HD+ 120Hz display", "13MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Infinix", "Infinix Smart 9 Pro 128GB 4GB RAM", 849, { v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }], specs: ["6.7\" HD+ 120Hz display", "50MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Infinix", "Infinix Hot 30 128GB 8GB RAM", 999, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" FHD+ 90Hz", "50MP + 0.08MP camera", "6000mAh 33W charging"] }],
  ["smartphones", "Infinix", "Infinix Hot 50 128GB 8GB RAM", 999, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" FHD+ 120Hz", "50MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Infinix", "Infinix Hot 50 Pro 256GB 8GB RAM", 1299, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" AMOLED 120Hz", "50MP dual camera", "5000mAh 33W charging"] }],
  ["smartphones", "Infinix", "Infinix Note 40 5G 256GB 8GB RAM", 1499, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" AMOLED 120Hz", "108MP + 2MP camera", "5000mAh 33W charging"] }],
  ["smartphones", "Infinix", "Infinix Note 50 256GB 8GB RAM", 1499, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.78\" AMOLED 120Hz", "50MP OIS camera", "5200mAh 45W charging"] }],
  ["smartphones", "Infinix", "Infinix Zero 40 256GB 12GB RAM", 2099, { v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.78\" AMOLED 144Hz", "108MP OIS camera", "5000mAh 45W charging"] }],
  ["smartphones", "Infinix", "Infinix GT 20 Pro 256GB 12GB RAM", 2299, { sale: "auto", v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.78\" AMOLED 144Hz", "108MP OIS camera", "5000mAh 45W charging"] }],
  ["smartphones", "Xiaomi", "Xiaomi Redmi A3x 64GB 3GB RAM", 599, { v: [{ n: "64GB / 3GB RAM", o: { Storage: "64GB", RAM: "3GB" }, d: 0 }, { n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 100 }], specs: ["6.71\" HD+ 90Hz", "8MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "Xiaomi", "Xiaomi Redmi 12 128GB 4GB RAM", 1149, { sale: "auto", v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }, { n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 250 }], specs: ["6.79\" FHD+ 90Hz", "50MP triple camera", "5000mAh battery"] }],
  ["smartphones", "Xiaomi", "Xiaomi Redmi 13 128GB 6GB RAM", 1249, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.79\" FHD+ 90Hz", "108MP dual camera", "5030mAh battery"] }],
  ["smartphones", "Xiaomi", "Xiaomi Redmi Note 14 128GB 8GB RAM", 1549, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 300 }], specs: ["6.67\" AMOLED 120Hz", "50MP + 2MP camera", "5500mAh 45W charging"] }],
  ["smartphones", "Xiaomi", "Xiaomi Redmi Note 14 Pro 256GB 8GB RAM", 2099, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.67\" AMOLED 120Hz", "200MP OIS camera", "5500mAh 45W charging"] }],
  ["smartphones", "Xiaomi", "Xiaomi POCO C65 128GB 6GB RAM", 1049, { sale: "auto", v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.74\" HD+ 90Hz", "50MP dual camera", "5000mAh 18W charging"] }],
  ["smartphones", "Xiaomi", "Xiaomi POCO X6 5G 256GB 8GB RAM", 2199, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.67\" AMOLED 120Hz", "64MP OIS camera", "5100mAh 67W charging"] }],
  ["smartphones", "Xiaomi", "Xiaomi POCO F6 5G 256GB 12GB RAM", 2999, { sale: "auto", v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.67\" AMOLED 120Hz", "50MP OIS camera", "5000mAh 90W charging"] }],
  ["smartphones", "Xiaomi", "Xiaomi 14T 256GB 12GB RAM", 3999, { v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.67\" AMOLED 144Hz", "50MP triple Leica camera", "5000mAh 67W charging"] }],
  ["smartphones", "OPPO", "OPPO A17 64GB 4GB RAM", 799, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.56\" HD+ 90Hz", "50MP dual camera", "5000mAh battery"] }],
  ["smartphones", "OPPO", "OPPO A38 128GB 4GB RAM", 949, { v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }], specs: ["6.56\" HD+ 90Hz", "50MP + 2MP camera", "5000mAh 33W charging"] }],
  ["smartphones", "OPPO", "OPPO A58 128GB 6GB RAM", 1099, { sale: "auto", v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.72\" FHD+ 90Hz", "50MP dual camera", "5000mAh 33W charging"] }],
  ["smartphones", "OPPO", "OPPO A78 128GB 6GB RAM", 1249, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 350 }], specs: ["6.43\" FHD+ 90Hz AMOLED", "50MP + 2MP camera", "5000mAh 67W charging"] }],
  ["smartphones", "OPPO", "OPPO A79 5G 128GB 8GB RAM", 1699, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.72\" FHD+ 90Hz", "50MP dual camera", "5000mAh 33W charging"] }],
  ["smartphones", "OPPO", "OPPO Reno 12 5G 256GB 12GB RAM", 3499, { sale: "auto", v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.7\" AMOLED 120Hz", "50MP OIS camera", "5000mAh 80W charging"] }],
  ["smartphones", "Honor", "Honor X6a 128GB 4GB RAM", 749, { sale: "auto", v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }], specs: ["6.56\" HD+ 90Hz", "50MP dual camera", "5200mAh battery"] }],
  ["smartphones", "Honor", "Honor X8a 128GB 8GB RAM", 1099, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" FHD+ 90Hz", "100MP triple camera", "4500mAh battery"] }],
  ["smartphones", "Honor", "Honor X9b 5G 256GB 12GB RAM", 2299, { sale: "auto", v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.78\" AMOLED 120Hz", "108MP OIS camera", "5800mAh battery"] }],
  ["smartphones", "Honor", "Honor 200 5G 256GB 12GB RAM", 3999, { v: [{ n: "256GB / 12GB RAM", o: { Storage: "256GB", RAM: "12GB" }, d: 0 }], specs: ["6.7\" AMOLED 120Hz", "50MP triple camera", "5200mAh 100W charging"] }],
  ["smartphones", "Realme", "Realme C53 128GB 6GB RAM", 949, { sale: "auto", v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.74\" HD+ 90Hz", "108MP + 0.08MP camera", "5000mAh 33W charging"] }],
  ["smartphones", "Realme", "Realme C55 128GB 6GB RAM", 1099, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 300 }], specs: ["6.72\" FHD+ 90Hz", "64MP dual camera", "5000mAh 33W charging"] }],
  ["smartphones", "Realme", "Realme Note 50 64GB 4GB RAM", 749, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.74\" HD+ 90Hz", "13MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Realme", "Realme 11 Pro 5G 256GB 8GB RAM", 2299, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" AMOLED 120Hz", "108MP OIS camera", "5000mAh 67W charging"] }],
  ["smartphones", "Motorola", "Motorola Moto G04 64GB 4GB RAM", 749, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.6\" HD+ 90Hz", "16MP camera", "5000mAh battery"] }],
  ["smartphones", "Motorola", "Motorola Moto G24 128GB 8GB RAM", 999, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.6\" FHD+ 90Hz", "50MP + 2MP camera", "5000mAh 30W charging"] }],
  ["smartphones", "Motorola", "Motorola Moto G54 5G 256GB 8GB RAM", 1499, { sale: "auto", v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.5\" FHD+ 120Hz", "50MP OIS camera", "6000mAh 33W charging"] }],
  ["smartphones", "Motorola", "Motorola Moto G84 5G 256GB 8GB RAM", 1999, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.5\" FHD+ 120Hz pOLED", "50MP OIS camera", "5000mAh 30W charging"] }],
  ["smartphones", "Nokia", "Nokia C12 64GB 2GB RAM", 549, { sale: "auto", v: [{ n: "64GB / 2GB RAM", o: { Storage: "64GB", RAM: "2GB" }, d: 0 }], specs: ["6.3\" HD+ display", "8MP camera", "4000mAh battery"] }],
  ["smartphones", "Nokia", "Nokia C22 64GB 4GB RAM", 649, { v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.5\" HD+ 90Hz", "13MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "Nokia", "Nokia C32 64GB 4GB RAM", 749, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.52\" HD+ 90Hz", "50MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "Nokia", "Nokia G22 128GB 6GB RAM", 1249, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.52\" FHD+ 90Hz", "50MP triple camera", "5050mAh battery"] }],
  ["smartphones", "itel", "itel A05s 32GB 2GB RAM", 399, { sale: "auto", v: [{ n: "32GB / 2GB RAM", o: { Storage: "32GB", RAM: "2GB" }, d: 0 }], specs: ["6.6\" HD+ display", "8MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "itel", "itel A50 32GB 2GB RAM", 459, { v: [{ n: "32GB / 2GB RAM", o: { Storage: "32GB", RAM: "2GB" }, d: 0 }], specs: ["6.6\" HD+ display", "8MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "itel", "itel A60 64GB 3GB RAM", 549, { sale: "auto", v: [{ n: "64GB / 3GB RAM", o: { Storage: "64GB", RAM: "3GB" }, d: 0 }], specs: ["6.6\" HD+ 90Hz", "8MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "itel", "itel A70 128GB 4GB RAM", 699, { v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }], specs: ["6.6\" HD+ 90Hz", "13MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "itel", "itel S24 128GB 4GB RAM", 999, { sale: "auto", v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }], specs: ["6.6\" FHD+ 90Hz", "50MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "itel", "itel P55 128GB 8GB RAM", 899, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.6\" FHD+ 90Hz", "50MP dual camera", "5000mAh battery"] }],
  ["smartphones", "Vivo", "Vivo Y02 32GB 2GB RAM", 549, { sale: "auto", v: [{ n: "32GB / 2GB RAM", o: { Storage: "32GB", RAM: "2GB" }, d: 0 }], specs: ["6.51\" HD+ display", "8MP camera", "5000mAh battery"] }],
  ["smartphones", "Vivo", "Vivo Y17s 64GB 4GB RAM", 799, { v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.56\" HD+ 90Hz", "50MP + 0.08MP camera", "5000mAh battery"] }],
  ["smartphones", "Vivo", "Vivo Y27 128GB 6GB RAM", 1149, { sale: "auto", v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.64\" FHD+ 90Hz", "50MP + 2MP camera", "5000mAh 44W charging"] }],
  ["smartphones", "Vivo", "Vivo Y36 128GB 8GB RAM", 1299, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 300 }], specs: ["6.64\" FHD+ 90Hz", "50MP + 2MP camera", "5000mAh 44W charging"] }],
  ["smartphones", "ZTE", "ZTE Blade A54 64GB 3GB RAM", 649, { sale: "auto", v: [{ n: "64GB / 3GB RAM", o: { Storage: "64GB", RAM: "3GB" }, d: 0 }], specs: ["6.6\" HD+ 90Hz", "13MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "ZTE", "ZTE Blade A75 5G 128GB 6GB RAM", 1199, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["6.6\" HD+ 90Hz", "50MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "TCL", "TCL 40 SE 128GB 4GB RAM", 899, { sale: "auto", v: [{ n: "128GB / 4GB RAM", o: { Storage: "128GB", RAM: "4GB" }, d: 0 }], specs: ["6.75\" FHD+ 90Hz", "50MP + 2MP camera", "5010mAh battery"] }],
  ["smartphones", "TCL", "TCL 405 64GB 2GB RAM", 599, { v: [{ n: "64GB / 2GB RAM", o: { Storage: "64GB", RAM: "2GB" }, d: 0 }], specs: ["6.6\" HD+ display", "13MP + 2MP camera", "5000mAh battery"] }],
  ["smartphones", "Huawei", "Huawei nova Y72 128GB 8GB RAM", 1299, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.75\" FHD+ 90Hz", "50MP + 2MP camera", "6000mAh battery"] }],
  ["smartphones", "Huawei", "Huawei nova 12i 256GB 8GB RAM", 1599, { v: [{ n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 0 }], specs: ["6.7\" FHD+ 90Hz", "108MP + 2MP camera", "5000mAh 40W charging"] }],
  ["smartphones", "OnePlus", "OnePlus Nord CE 3 Lite 5G 128GB 8GB RAM", 1899, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["6.72\" FHD+ 120Hz", "108MP + 2MP + 2MP camera", "5000mAh 67W charging"] }],
  ["smartphones", "Blackview", "Blackview A60 32GB 2GB RAM", 499, { v: [{ n: "32GB / 2GB RAM", o: { Storage: "32GB", RAM: "2GB" }, d: 0 }], specs: ["6.1\" HD+ display", "8MP + 0.3MP camera", "4780mAh battery"] }],
  ["smartphones", "Blackview", "Blackview BV6200 Rugged 64GB 4GB RAM", 1299, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["6.56\" HD+ 90Hz", "13MP + 0.3MP camera", "13000mAh battery"] }],

  // ============ Feature Phones ============
  ["feature-phones", "Nokia", "Nokia 105 4G Dual SIM", 349, { new: true, specs: ["2.2\" QQVGA display", "4G LTE", "1000mAh battery", "FM radio"] }],
  ["feature-phones", "Nokia", "Nokia 110 4G Dual SIM", 399, { specs: ["2.4\" QVGA display", "4G LTE", "1450mAh battery", "Camera + torch"] }],
  ["feature-phones", "Nokia", "Nokia 125 2.4 Dual SIM", 299, { specs: ["2.4\" QVGA display", "2G", "1020mAh battery", "FM radio"] }],
  ["feature-phones", "Nokia", "Nokia 130 Music Dual SIM", 329, { specs: ["2.4\" QVGA display", "2G", "1450mAh battery", "MP3 player"] }],
  ["feature-phones", "Nokia", "Nokia 150 2G Dual SIM", 379, { specs: ["2.4\" QVGA display", "2G", "1450mAh battery", "0.3MP camera"] }],
  ["feature-phones", "Nokia", "Nokia 215 4G Dual SIM", 429, { new: true, specs: ["2.8\" QVGA display", "4G LTE", "1450mAh battery", "Snake game"] }],
  ["feature-phones", "Nokia", "Nokia 235 4G Dual SIM", 499, { specs: ["2.8\" QVGA display", "4G LTE", "1450mAh battery", "2MP camera"] }],
  ["feature-phones", "Nokia", "Nokia 3210 4G Dual SIM", 549, { new: true, specs: ["2.4\" QVGA display", "4G LTE", "1450mAh battery", "Snake game"] }],
  ["feature-phones", "Nokia", "Nokia 3310 4G Dual SIM", 599, { specs: ["2.4\" QVGA display", "4G LTE", "1200mAh battery", "Snake game"] }],
  ["feature-phones", "itel", "itel 2160 Dual SIM", 249, { specs: ["2.4\" QVGA display", "2G", "1000mAh battery", "Torch"] }],
  ["feature-phones", "itel", "itel 2170 Dual SIM", 269, { specs: ["2.4\" QVGA display", "2G", "1000mAh battery", "Torch + FM radio"] }],
  ["feature-phones", "itel", "itel 2216 Dual SIM", 299, { specs: ["2.4\" QVGA display", "2G", "2500mAh battery", "Long standby"] }],
  ["feature-phones", "itel", "itel 2234 Dual SIM", 289, { new: true, specs: ["2.4\" QVGA display", "2G", "1800mAh battery", "Flash torch"] }],
  ["feature-phones", "itel", "itel 2250 Dual SIM", 329, { specs: ["2.8\" QVGA display", "2G", "2500mAh battery", "MP3 + camera"] }],
  ["feature-phones", "Tecno", "Tecno T420 Dual SIM", 219, { specs: ["2.4\" QVGA display", "2G", "800mAh battery", "Torch"] }],
  ["feature-phones", "Tecno", "Tecno T431 Dual SIM", 239, { specs: ["2.4\" QVGA display", "2G", "1000mAh battery", "FM radio"] }],
  ["feature-phones", "Tecno", "Tecno T471 Dual SIM", 289, { new: true, specs: ["2.4\" QVGA display", "2G", "1500mAh battery", "Torch + camera"] }],
  ["feature-phones", "Tecno", "Tecno T473 Dual SIM", 329, { specs: ["2.8\" QVGA display", "4G LTE", "1500mAh battery", "WhatsApp-ready OS"] }],
  ["feature-phones", "Infinix", "Infinix X650 Dual SIM", 259, { specs: ["2.4\" QVGA display", "2G", "1500mAh battery", "Torch"] }],
  ["feature-phones", "Samsung", "Samsung Guru Music 2 Dual SIM", 429, { specs: ["2.4\" QVGA display", "2G", "800mAh battery", "Music player"] }],
  ["feature-phones", "Samsung", "Samsung Metro 2 Dual SIM", 499, { specs: ["2.4\" QVGA display", "2G", "1200mAh battery", "Snake + music"] }],
  ["feature-phones", "Alcatel", "Alcatel 1052 Dual SIM", 229, { specs: ["1.8\" display", "2G", "500mAh battery", "Torch"] }],
  ["feature-phones", "Alcatel", "Alcatel 2053 Dual SIM", 349, { specs: ["2.4\" QVGA display", "2G", "1000mAh battery", "Camera + MP3"] }],
  ["feature-phones", "Nokia", "Nokia 2720 Flip 4G", 649, { new: true, specs: ["2.8\" main + 1.3\" cover display", "4G LTE", "1500mAh battery", "Loud buttons"] }],
  ["feature-phones", "Nokia", "Nokia 8000 4G Dual SIM", 849, { specs: ["2.8\" QVGA display", "4G LTE", "1500mAh battery", "Curved glass design"] }],
  ["feature-phones", "itel", "itel it2323 Dual SIM", 319, { specs: ["2.8\" QVGA display", "2G", "2500mAh battery", "Camera"] }],

  // ============ Refurbished Phones (UK Used / Grade A) ============
  ["refurbished-phones", "Apple", "Refurbished Apple iPhone XS Max 64GB UK Used", 1499, { sale: "auto", v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 400 }], specs: ["6.5\" Super Retina OLED", "Dual 12MP camera", "Face ID", "Grade A UK used"] }],
  ["refurbished-phones", "Apple", "Refurbished Apple iPhone 11 Pro 128GB UK Used", 2299, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["5.8\" Super Retina XDR", "Triple 12MP camera", "18W fast charging", "Grade A UK used"] }],
  ["refurbished-phones", "Apple", "Refurbished Apple iPhone 13 Pro Max 256GB UK Used", 3899, { sale: "auto", v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.7\" ProMotion XDR", "Triple 12MP camera", "A15 Bionic", "Grade A UK used"] }],
  ["refurbished-phones", "Apple", "Refurbished Apple iPhone 14 Pro 256GB UK Used", 4799, { v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.1\" ProMotion XDR", "48MP triple camera", "Dynamic Island", "Grade A UK used"] }],
  ["refurbished-phones", "Samsung", "Refurbished Samsung Galaxy S21 5G 128GB UK Used", 1899, { sale: "auto", v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["6.2\" AMOLED 120Hz", "Triple 64MP camera", "IP68", "Grade A UK used"] }],
  ["refurbished-phones", "Samsung", "Refurbished Samsung Galaxy S22 Ultra 256GB UK Used", 3699, { v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.8\" AMOLED 120Hz", "108MP quad camera", "S Pen included", "Grade A UK used"] }],
  ["refurbished-phones", "Samsung", "Refurbished Samsung Galaxy Note 20 128GB UK Used", 2299, { sale: "auto", v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["6.7\" AMOLED 60Hz", "64MP triple camera", "S Pen included", "Grade A UK used"] }],
  ["refurbished-phones", "Samsung", "Refurbished Samsung Galaxy A53 5G 128GB UK Used", 1299, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["6.5\" AMOLED 120Hz", "64MP quad camera", "5000mAh battery", "Grade A UK used"] }],
  ["refurbished-phones", "Apple", "Refurbished Apple iPhone 12 Pro 256GB UK Used", 2899, { sale: "auto", v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.1\" Super Retina XDR", "Triple 12MP camera", "LiDAR scanner", "Grade A UK used"] }],
  ["refurbished-phones", "Samsung", "Refurbished Samsung Galaxy Z Flip 4 256GB UK Used", 2899, { v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.7\" Foldable AMOLED", "Dual 12MP camera", "IPX8", "Grade A UK used"] }],
  ["refurbished-phones", "Google", "Refurbished Google Pixel 7 Pro 128GB UK Used", 2799, { sale: "auto", v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["6.7\" LTPO OLED 120Hz", "50MP triple camera", "Tensor G2", "Grade A UK used"] }],
  ["refurbished-phones", "Google", "Refurbished Google Pixel 8 128GB UK Used", 2999, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["6.2\" OLED 120Hz", "50MP dual camera", "Tensor G3", "Grade A UK used"] }],
  ["refurbished-phones", "Apple", "Refurbished Apple iPhone SE (2020) 128GB UK Used", 1199, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["4.7\" Retina HD", "12MP camera", "Touch ID", "Grade A UK used"] }],
  ["refurbished-phones", "Huawei", "Refurbished Huawei P30 Pro 256GB UK Used", 1699, { sale: "auto", v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["6.47\" OLED", "40MP quad camera", "Leica optics", "Grade A UK used"] }],
  ["refurbished-phones", "Xiaomi", "Refurbished Xiaomi Redmi Note 11 128GB UK Used", 1099, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["6.43\" AMOLED 90Hz", "50MP quad camera", "5000mAh battery", "Grade A UK used"] }],

  // ============ Android Tablets ============
  ["android-tablets", "Samsung", "Samsung Galaxy Tab A9 64GB 4GB RAM Wi-Fi", 1199, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["8.7\" TFT 90Hz", "8MP + 2MP camera", "5100mAh battery"] }],
  ["android-tablets", "Samsung", "Samsung Galaxy Tab A9+ 64GB 4GB RAM Wi-Fi", 1499, { v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }, { n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 500 }], specs: ["11\" TFT 90Hz", "8MP + 5MP camera", "7040mAh battery"] }],
  ["android-tablets", "Samsung", "Samsung Galaxy Tab A7 Lite 32GB 3GB RAM", 949, { sale: "auto", v: [{ n: "32GB / 3GB RAM", o: { Storage: "32GB", RAM: "3GB" }, d: 0 }], specs: ["8.7\" TFT", "8MP + 2MP camera", "5100mAh battery"] }],
  ["android-tablets", "Samsung", "Samsung Galaxy Tab S6 Lite 64GB 4GB RAM", 2799, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["10.4\" TFT", "8MP + 5MP camera", "7040mAh battery", "S Pen included"] }],
  ["android-tablets", "Samsung", "Samsung Galaxy Tab S9 FE 128GB 6GB RAM", 3999, { v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["10.9\" IPS 90Hz", "8MP + 8MP camera", "8000mAh battery", "IP68"] }],
  ["android-tablets", "Lenovo", "Lenovo Tab M10 5G 64GB 4GB RAM", 1199, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["10.6\" IPS 60Hz", "8MP camera", "7700mAh battery"] }],
  ["android-tablets", "Lenovo", "Lenovo Tab M11 64GB 4GB RAM", 1299, { v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }, { n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 450 }], specs: ["10.95\" IPS 90Hz", "13MP + 8MP camera", "7040mAh battery"] }],
  ["android-tablets", "Lenovo", "Lenovo Tab P12 128GB 8GB RAM", 2499, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["12.7\" 3K IPS 120Hz", "13MP + 8MP camera", "10200mAh battery"] }],
  ["android-tablets", "Xiaomi", "Xiaomi Redmi Pad SE 128GB 6GB RAM", 1499, { sale: "auto", v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }], specs: ["11\" FHD+ 90Hz", "8MP + 5MP camera", "8000mAh battery"] }],
  ["android-tablets", "Xiaomi", "Xiaomi Redmi Pad Pro 128GB 8GB RAM", 2199, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["12.1\" 2.5K 120Hz", "8MP + 8MP camera", "10000mAh battery"] }],
  ["android-tablets", "Xiaomi", "Xiaomi Pad 6 128GB 6GB RAM", 2799, { sale: "auto", v: [{ n: "128GB / 6GB RAM", o: { Storage: "128GB", RAM: "6GB" }, d: 0 }, { n: "256GB / 8GB RAM", o: { Storage: "256GB", RAM: "8GB" }, d: 700 }], specs: ["11\" 2.8K 144Hz", "13MP + 8MP camera", "8840mAh battery"] }],
  ["android-tablets", "Tecno", "Tecno Megapad 10 64GB 4GB RAM", 949, { v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["10.36\" IPS 60Hz", "8MP + 5MP camera", "7000mAh battery"] }],
  ["android-tablets", "Tecno", "Tecno Megapad 11 128GB 8GB RAM", 1299, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["11\" IPS 90Hz", "13MP + 8MP camera", "8000mAh battery"] }],
  ["android-tablets", "Infinix", "Infinix XPad 128GB 8GB RAM", 1399, { v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["11\" IPS 90Hz", "13MP + 8MP camera", "7000mAh battery"] }],
  ["android-tablets", "itel", "itel Pad 1 64GB 4GB RAM", 699, { sale: "auto", v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["10\" IPS 60Hz", "8MP + 5MP camera", "7000mAh battery"] }],
  ["android-tablets", "Nokia", "Nokia T21 64GB 4GB RAM", 1199, { v: [{ n: "64GB / 4GB RAM", o: { Storage: "64GB", RAM: "4GB" }, d: 0 }], specs: ["10.36\" IPS 60Hz", "8MP + 8MP camera", "8200mAh battery"] }],
  ["android-tablets", "Huawei", "Huawei MatePad 11.5 128GB 8GB RAM", 2199, { sale: "auto", v: [{ n: "128GB / 8GB RAM", o: { Storage: "128GB", RAM: "8GB" }, d: 0 }], specs: ["11.5\" 2.2K 120Hz", "13MP + 8MP camera", "7700mAh battery"] }],
  ["android-tablets", "Amazon", "Amazon Fire 7 (2022) 16GB", 549, { v: [{ n: "16GB", o: { Storage: "16GB" }, d: 0 }], specs: ["7\" IPS", "2MP camera", "Alexa built-in"] }],
  ["android-tablets", "Amazon", "Amazon Fire HD 8 (2022) 32GB", 749, { sale: "auto", v: [{ n: "32GB", o: { Storage: "32GB" }, d: 0 }, { n: "64GB", o: { Storage: "64GB" }, d: 200 }], specs: ["8\" HD display", "2MP camera", "Alexa built-in"] }],
  ["android-tablets", "Amazon", "Amazon Fire HD 10 (2023) 32GB", 949, { v: [{ n: "32GB", o: { Storage: "32GB" }, d: 0 }, { n: "64GB", o: { Storage: "64GB" }, d: 200 }], specs: ["10.1\" FHD display", "5MP camera", "Alexa built-in"] }],
  ["android-tablets", "Alcatel", "Alcatel 1T 10 32GB 2GB RAM", 599, { sale: "auto", v: [{ n: "32GB / 2GB RAM", o: { Storage: "32GB", RAM: "2GB" }, d: 0 }], specs: ["10\" IPS 60Hz", "5MP + 2MP camera", "4080mAh battery"] }],

  // ============ iPad ============
  ["ipads", "Apple", "Apple iPad 10th Gen 64GB Wi-Fi", 3999, { sale: "auto", v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 1200 }], specs: ["10.9\" Liquid Retina", "12MP + 12MP camera", "A14 Bionic"] }],
  ["ipads", "Apple", "Apple iPad 10th Gen 64GB Wi-Fi + Cellular", 5099, { v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }], specs: ["10.9\" Liquid Retina", "12MP + 12MP camera", "5G cellular"] }],
  ["ipads", "Apple", "Apple iPad Air 5th Gen 64GB Wi-Fi", 6999, { sale: "auto", v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }, { n: "256GB", o: { Storage: "256GB" }, d: 1600 }], specs: ["10.9\" Liquid Retina", "12MP camera", "M1 chip"] }],
  ["ipads", "Apple", "Apple iPad Air 11-inch M2 128GB Wi-Fi", 8999, { v: [{ n: "128GB", o: { Storage: "128GB" }, d: 0 }], specs: ["11\" Liquid Retina", "12MP camera", "M2 chip"] }],
  ["ipads", "Apple", "Apple iPad Mini 6th Gen 64GB Wi-Fi", 5999, { sale: "auto", v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }], specs: ["8.3\" Liquid Retina", "12MP camera", "A15 Bionic"] }],
  ["ipads", "Apple", "Apple iPad Pro 11-inch M4 256GB Wi-Fi", 14999, { v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["11\" Ultra Retina XDR", "12MP camera", "M4 chip"] }],
  ["ipads", "Apple", "Apple iPad Pro 13-inch M4 256GB Wi-Fi", 19999, { sale: "auto", v: [{ n: "256GB", o: { Storage: "256GB" }, d: 0 }], specs: ["13\" Ultra Retina XDR", "12MP camera", "M4 chip"] }],
  ["ipads", "Apple", "Apple iPad 9th Gen 64GB Wi-Fi", 3399, { sale: "auto", v: [{ n: "64GB", o: { Storage: "64GB" }, d: 0 }], specs: ["10.2\" Retina", "8MP + 12MP camera", "A13 Bionic"] }],

  // ============ Phone Cases ============
  ["phone-cases", "Spigen", "Spigen Liquid Air Case for Samsung Galaxy A15", 149, { sale: "auto", colors: ["Matte Black", "Navy", "Blue"] }],
  ["phone-cases", "Spigen", "Spigen Liquid Air Case for Samsung Galaxy A55", 159, { colors: ["Matte Black", "Navy", "Blue"] }],
  ["phone-cases", "Spigen", "Spigen Rugged Armor Case for iPhone 15", 199, { sale: "auto", colors: ["Black", "Navy"] }],
  ["phone-cases", "Spigen", "Spigen Ultra Hybrid Clear Case for iPhone 15 Pro", 189, { colors: ["Clear", "Matte Clear"] }],
  ["phone-cases", "Ringke", "Ringke Fusion Clear Case for Samsung Galaxy A05", 99, { sale: "auto", colors: ["Clear", "Smoke Black"] }],
  ["phone-cases", "Ringke", "Ringke Fusion-X Case for Samsung Galaxy A35", 129, { colors: ["Clear Black", "Clear Blue"] }],
  ["phone-cases", "Ringke", "Ringke Onyx Case for iPhone 14", 159, { colors: ["Black", "Navy", "Mint"] }],
  ["phone-cases", "Nillkin", "Nillkin Nature TPU Case for Samsung Galaxy A16", 89, { sale: "auto", colors: ["Black", "Red"] }],
  ["phone-cases", "Nillkin", "Nillkin Frosted Shield Case for Samsung Galaxy S24", 129, { colors: ["Black", "Blue", "Red"] }],
  ["phone-cases", "Nillkin", "Nillkin CamShield Pro Case for iPhone 15 Pro Max", 199, { colors: ["Black", "Blue"] }],
  ["phone-cases", "Baseus", "Baseus Smart Case for Samsung Galaxy A54", 119, { sale: "auto", colors: ["Black", "Green"] }],
  ["phone-cases", "Baseus", "Baseus Slim Case for iPhone 13", 99, { colors: ["Black", "Clear", "Pink"] }],
  ["phone-cases", "Oraimo", "Oraimo Soft TPU Case for Tecno Spark 20", 49, { sale: "auto", colors: ["Black", "Blue", "Red"] }],
  ["phone-cases", "Oraimo", "Oraimo Shockproof Case for Infinix Hot 40", 55, { colors: ["Black", "Navy"] }],
  ["phone-cases", "Oraimo", "Oraimo Case for itel A70", 45, { colors: ["Black", "Blue"] }],
  ["phone-cases", "UAG", "UAG Pathfinder Case for iPhone 15 Pro", 399, { sale: "auto", colors: ["Black", "Green"] }],
  ["phone-cases", "UAG", "UAG Plasma Case for Samsung Galaxy S24 Ultra", 449, { colors: ["Black", "Ash"] }],
  ["phone-cases", "OtterBox", "OtterBox Defender Case for iPhone 15", 599, { sale: "auto", colors: ["Black", "Forest"] }],
  ["phone-cases", "OtterBox", "OtterBox Commuter Case for Samsung Galaxy A55", 549, { colors: ["Black", "Navy"] }],
  ["phone-cases", "ESR", "ESR Clear Case for iPhone 14", 89, { sale: "auto", colors: ["Clear", "Smoke"] }],
  ["phone-cases", "ESR", "ESR Shockproof Case for Samsung Galaxy A35", 79, { colors: ["Black", "Red"] }],
  ["phone-cases", "Awei", "Awei Ultra-Thin Case for iPhone 12", 45, { sale: "auto", colors: ["Black", "White", "Blue", "Pink"] }],
  ["phone-cases", "Awei", "Awei Silicone Case for Xiaomi Redmi Note 13", 39, { colors: ["Black", "Blue", "Green"] }],
  ["phone-cases", "Samsung", "Samsung Leather Cover for Galaxy S25", 249, { colors: ["Black", "Brown"] }],
  ["phone-cases", "Samsung", "Samsung Silicone Cover for Galaxy A55", 149, { colors: ["Black", "Mint", "Yellow"] }],
  ["phone-cases", "Apple", "Apple Silicone Case for iPhone 15", 449, { sale: "auto", colors: ["Black", "White", "Blue", "Orange"] }],
  ["phone-cases", "Apple", "Apple Clear Case for iPhone 15 Pro", 449, { colors: ["Clear"] }],
  ["phone-cases", "ZAGG", "ZAGG Gear4 Brooklyn Case for iPhone 14", 449, { colors: ["Black", "Blue"] }],
  ["phone-cases", "UAG", "UAG Monarch Pro Case for iPhone 15 Pro Max", 499, { sale: "auto", colors: ["Black", "Red"] }],
  ["phone-cases", "Oraimo", "Oraimo Case for Realme C53", 49, { colors: ["Black", "Blue"] }],
  ["phone-cases", "Baseus", "Baseus Magnetic Clear Case for iPhone 15", 149, { colors: ["Clear", "Black"] }],

  // ============ Screen Protectors ============
  ["screen-protectors", "Nillkin", "Nillkin 9H Tempered Glass for Samsung Galaxy A15", 49, { sale: "auto", colors: ["Clear", "Matte"] }],
  ["screen-protectors", "Nillkin", "Nillkin 9H Tempered Glass for iPhone 15", 59, { colors: ["Clear"] }],
  ["screen-protectors", "Nillkin", "Nillkin CP+ Pro Screen Protector for Samsung Galaxy S24", 99, { sale: "auto", colors: ["Clear"] }],
  ["screen-protectors", "Spigen", "Spigen GlasTR EZ Fit for iPhone 15 Pro", 199, { colors: ["Clear"] }],
  ["screen-protectors", "Spigen", "Spigen GlasTR Align Master for Samsung Galaxy A55", 149, { colors: ["Clear"] }],
  ["screen-protectors", "Ringke", "Ringke Dual Easy Film for iPhone 13", 99, { sale: "auto", colors: ["Clear"] }],
  ["screen-protectors", "Baseus", "Baseus Tempered Glass for Tecno Camon 30", 39, { colors: ["Clear", "Matte"] }],
  ["screen-protectors", "Baseus", "Baseus Tempered Glass for Infinix Note 40", 39, { colors: ["Clear", "Matte"] }],
  ["screen-protectors", "Oraimo", "Oraimo Tempered Glass for itel A70", 25, { sale: "auto", colors: ["Clear"] }],
  ["screen-protectors", "Oraimo", "Oraimo Tempered Glass for Tecno Spark 20", 25, { colors: ["Clear"] }],
  ["screen-protectors", "ESR", "ESR Tempered Glass for iPhone 14", 49, { sale: "auto", colors: ["Clear"] }],
  ["screen-protectors", "ESR", "ESR Privacy Screen Protector for Samsung Galaxy S24 Ultra", 129, { colors: ["Clear"] }],
  ["screen-protectors", "ZAGG", "ZAGG InvisibleShield Glass Elite for iPhone 15 Pro Max", 449, { sale: "auto", colors: ["Clear"] }],
  ["screen-protectors", "Paperlike", "Paperlike Screen Protector for iPad 10th Gen", 399, { colors: ["Clear"] }],
  ["screen-protectors", "Nillkin", "Nillkin Tempered Glass for Xiaomi Redmi Note 13", 45, { sale: "auto", colors: ["Clear"] }],
  ["screen-protectors", "Baseus", "Baseus Full Cover Glass for iPhone 15 Plus", 59, { colors: ["Clear"] }],
  ["screen-protectors", "Oraimo", "Oraimo 9H Glass for Infinix Hot 50", 29, { colors: ["Clear"] }],
  ["screen-protectors", "Nillkin", "Nillkin Nature Glass for Samsung Galaxy Z Flip5", 129, { sale: "auto", colors: ["Clear"] }],

  // ============ Chargers ============
  ["chargers", "Anker", "Anker 511 Charger 20W USB-C Power Adapter", 199, { sale: "auto", colors: ["Black", "White"] }],
  ["chargers", "Anker", "Anker 735 Charger 65W GaN Dual USB-C", 499, { colors: ["Black", "White"] }],
  ["chargers", "Anker", "Anker 511 Nano 3 30W USB-C Charger", 249, { sale: "auto", colors: ["Black", "White"] }],
  ["chargers", "Anker", "Anker 736 Charger 100W GaN 3-Port", 799, { colors: ["Black"] }],
  ["chargers", "Samsung", "Samsung 25W USB-C Power Adapter EP-T2510", 249, { sale: "auto", colors: ["White", "Black"] }],
  ["chargers", "Samsung", "Samsung 45W USB-C Super Fast Charger EP-T4510", 399, { colors: ["Black"] }],
  ["chargers", "Apple", "Apple 20W USB-C Power Adapter", 299, { colors: ["White"] }],
  ["chargers", "Apple", "Apple 35W Dual USB-C Power Adapter", 449, { colors: ["White"] }],
  ["chargers", "Baseus", "Baseus GaN5 65W USB-C Charger", 349, { sale: "auto", colors: ["Black", "White"] }],
  ["chargers", "Baseus", "Baseus 20W USB-C Charger", 129, { colors: ["White", "Black"] }],
  ["chargers", "UGREEN", "UGREEN Nexode 65W GaN USB-C Charger", 399, { sale: "auto", colors: ["Black"] }],
  ["chargers", "UGREEN", "UGREEN 30W USB-C Fast Charger", 199, { colors: ["Black", "White"] }],
  ["chargers", "Oraimo", "Oraimo 20W USB-C Charger", 99, { sale: "auto", colors: ["White", "Black"] }],
  ["chargers", "Oraimo", "Oraimo 3-Port Wall Charger 25W", 129, { colors: ["White"] }],
  ["chargers", "Awei", "Awei 10W USB Charger 2-Port", 49, { sale: "auto", colors: ["White", "Black"] }],
  ["chargers", "Belkin", "Belkin 65W GaN Charger 2-Port", 549, { colors: ["Black"] }],
  ["chargers", "Tecno", "Tecno 70W Original Charger for Camon 30", 249, { colors: ["White", "Black"] }],
  ["chargers", "Infinix", "Infinix 45W Original Charger for Note 50", 229, { colors: ["White", "Black"] }],
  ["chargers", "Xiaomi", "Xiaomi 67W USB-C Charger", 299, { sale: "auto", colors: ["White"] }],
  ["chargers", "OPPO", "OPPO 67W SUPERVOOC Charger", 349, { colors: ["White"] }],
  ["chargers", "Huawei", "Huawei 40W SuperCharge Adapter", 349, { colors: ["White"] }],

  // ============ Fast Chargers ============
  ["fast-chargers", "Anker", "Anker 313 Ace 45W Fast Charger", 349, { sale: "auto", colors: ["Black"] }],
  ["fast-chargers", "Anker", "Anker 737 PowerPort 120W 4-Port GaN Charger", 999, { colors: ["Black"] }],
  ["fast-chargers", "Baseus", "Baseus GaN2 100W Charger 4-Port", 649, { sale: "auto", colors: ["Black", "White"] }],
  ["fast-chargers", "UGREEN", "UGREEN Nexode 100W GaN Charger", 699, { colors: ["Black"] }],
  ["fast-chargers", "Belkin", "Belkin BoostCharge 45W USB-C GaN Charger", 649, { sale: "auto", colors: ["Black"] }],
  ["fast-chargers", "Samsung", "Samsung 15W Super Fast Charger EP-TA800", 179, { colors: ["Black", "White"] }],
  ["fast-chargers", "Oraimo", "Oraimo 45W Fast Charger for Note 40", 159, { sale: "auto", colors: ["Black"] }],
  ["fast-chargers", "Xiaomi", "Xiaomi 120W HyperCharge Adapter", 499, { colors: ["White"] }],
  ["fast-chargers", "OPPO", "OPPO 80W SUPERVOOC Flash Charger", 449, { colors: ["White"] }],
  ["fast-chargers", "Tecno", "Tecno 45W Fast Charger for Pova 6", 199, { sale: "auto", colors: ["White"] }],
  ["fast-chargers", "Infinix", "Infinix 33W Charger with Type-C Cable", 149, { colors: ["Black"] }],
  ["fast-chargers", "Vention", "Vention 65W GaN Charger 3-Port", 399, { colors: ["Black"] }],

  // ============ USB Cables ============
  ["usb-cables", "Anker", "Anker PowerLine II 3-in-1 Cable 1.2m", 199, { sale: "auto", colors: ["Black"] }],
  ["usb-cables", "Anker", "Anker PowerLine USB-C to Lightning 1.8m", 149, { colors: ["Black", "White"] }],
  ["usb-cables", "Anker", "Anker 543 USB-C to USB-C Cable 1.8m 100W", 249, { colors: ["Black"] }],
  ["usb-cables", "Baseus", "Baseus 100W USB-C to USB-C Cable 2m", 129, { sale: "auto", colors: ["Black", "Blue"] }],
  ["usb-cables", "Baseus", "Baseus 3-in-1 Braided Cable 1.2m", 99, { colors: ["Black", "Red"] }],
  ["usb-cables", "UGREEN", "UGREEN USB-C to Lightning MFi Cable 1m", 199, { sale: "auto", colors: ["White"] }],
  ["usb-cables", "UGREEN", "UGREEN 60W USB-C Cable 1m", 89, { colors: ["Black", "White"] }],
  ["usb-cables", "Oraimo", "Oraimo Type-C Fast Charge Cable 1m", 45, { sale: "auto", colors: ["Black", "White"] }],
  ["usb-cables", "Oraimo", "Oraimo Micro USB Cable 1m", 35, { colors: ["Black", "White"] }],
  ["usb-cables", "Awei", "Awei 3-in-1 Charging Cable 1.2m", 35, { sale: "auto", colors: ["Black", "Red", "Blue"] }],
  ["usb-cables", "Awei", "Awei USB-C Cable 2m", 29, { colors: ["Black", "White"] }],
  ["usb-cables", "Belkin", "Belkin BoostCharge Braided USB-C to Lightning 1m", 399, { colors: ["Black", "Blue"] }],
  ["usb-cables", "Apple", "Apple USB-C to Lightning Cable 1m", 299, { colors: ["White"] }],
  ["usb-cables", "Samsung", "Samsung USB-C to USB-C Cable EP-DX510 1m", 149, { sale: "auto", colors: ["Black", "White"] }],
  ["usb-cables", "Tecno", "Tecno Original Type-C Cable 1m", 49, { colors: ["White", "Black"] }],
  ["usb-cables", "Infinix", "Infinix Original Type-C Cable 1m", 45, { colors: ["White", "Black"] }],
  ["usb-cables", "Nillkin", "Nillkin M-Series USB-C Cable 1m", 39, { sale: "auto", colors: ["Black", "Blue"] }],
  ["usb-cables", "Vention", "Vention USB-C to Lightning MFi 1.2m", 129, { colors: ["White", "Black"] }],
  ["usb-cables", "Xiaomi", "Xiaomi Type-C to 3.5mm Adapter Cable", 59, { colors: ["White"] }],

  // ============ Power Banks ============
  ["power-banks", "Anker", "Anker PowerCore 10000mAh 12W Power Bank", 349, { sale: "auto", colors: ["Black", "White"] }],
  ["power-banks", "Anker", "Anker PowerCore 20000mAh 22.5W Power Bank", 649, { colors: ["Black", "White"] }],
  ["power-banks", "Anker", "Anker PowerCore Slim 10000mAh PD 20W", 499, { sale: "auto", colors: ["Black", "Blue"] }],
  ["power-banks", "Anker", "Anker 521 Power Bank 20000mAh 65W", 899, { colors: ["Black"] }],
  ["power-banks", "Baseus", "Baseus 20000mAh 22.5W Digital Display Power Bank", 449, { sale: "auto", colors: ["Black", "White"] }],
  ["power-banks", "Baseus", "Baseus 10000mAh 20W Slim Power Bank", 299, { colors: ["Black", "White", "Pink"] }],
  ["power-banks", "Oraimo", "Oraimo 10000mAh Power Bank", 199, { sale: "auto", colors: ["Black", "White"] }],
  ["power-banks", "Oraimo", "Oraimo 20000mAh Power Bank 22.5W", 349, { colors: ["Black"] }],
  ["power-banks", "Oraimo", "Oraimo 5000mAh Mini Power Bank", 129, { colors: ["Black", "White", "Blue", "Pink"] }],
  ["power-banks", "Romoss", "Romoss 10000mAh Sense 8 Power Bank", 249, { sale: "auto", colors: ["Black", "White"] }],
  ["power-banks", "Romoss", "Romoss 20000mAh 22.5W Power Bank", 429, { colors: ["Black"] }],
  ["power-banks", "Xiaomi", "Xiaomi Mi Power Bank 3 10000mAh", 299, { sale: "auto", colors: ["Black", "White"] }],
  ["power-banks", "Xiaomi", "Xiaomi Mi Power Bank 3 20000mAh", 429, { colors: ["Black"] }],
  ["power-banks", "Awei", "Awei 10000mAh Power Bank", 149, { sale: "auto", colors: ["Black", "White", "Blue"] }],
  ["power-banks", "Awei", "Awei 20000mAh Power Bank", 229, { colors: ["Black"] }],
  ["power-banks", "Samsung", "Samsung 10000mAh 25W Power Bank", 449, { colors: ["Black", "White"] }],
  ["power-banks", "UGREEN", "UGREEN 20000mAh 45W Power Bank", 649, { sale: "auto", colors: ["Black"] }],
  ["power-banks", "Energizer", "Energizer 10000mAh Power Bank", 249, { colors: ["Black", "Red"] }],
  ["power-banks", "Duracell", "Duracell 10000mAh Power Bank", 269, { colors: ["Black", "Blue"] }],
  ["power-banks", "Belkin", "Belkin 10000mAh Power Bank 20W", 499, { colors: ["Black"] }],

  // ============ Wireless Chargers ============
  ["wireless-chargers", "Anker", "Anker 313 Wireless Charger 15W", 299, { sale: "auto", colors: ["Black", "White"] }],
  ["wireless-chargers", "Anker", "Anker PowerWave Stand 10W", 249, { colors: ["Black", "White"] }],
  ["wireless-chargers", "Samsung", "Samsung Wireless Charger Duo Pad 9W", 349, { colors: ["Black"] }],
  ["wireless-chargers", "Belkin", "Belkin 15W Wireless Charging Stand", 449, { sale: "auto", colors: ["Black", "White"] }],
  ["wireless-chargers", "Baseus", "Baseus 15W Wireless Charger 3-in-1", 399, { colors: ["Black", "White"] }],
  ["wireless-chargers", "Oraimo", "Oraimo 15W Wireless Charger", 179, { sale: "auto", colors: ["Black", "White"] }],
  ["wireless-chargers", "Awei", "Awei 15W Fast Wireless Charger", 129, { colors: ["Black", "White"] }],
  ["wireless-chargers", "ESR", "ESR HaloLock 15W Wireless Charger", 249, { colors: ["Black"] }],
  ["wireless-chargers", "UGREEN", "UGREEN 15W Wireless Charging Pad", 249, { sale: "auto", colors: ["Black"] }],
  ["wireless-chargers", "Nillkin", "Nillkin 15W Wireless Charger", 149, { colors: ["Black", "White"] }],
  ["wireless-chargers", "Xiaomi", "Xiaomi 50W Wireless Charging Stand Pro", 399, { colors: ["Black"] }],
  ["wireless-chargers", "Samsung", "Samsung Super Fast Wireless Charger 15W", 449, { colors: ["Black"] }],

  // ============ Phone Holders ============
  ["phone-holders", "Lamicall", "Lamicall Car Mount Holder Magnetic", 129, { sale: "auto", colors: ["Black", "Silver"] }],
  ["phone-holders", "Lamicall", "Lamicall Desk Stand Phone Holder", 99, { colors: ["Black", "Silver", "Blue"] }],
  ["phone-holders", "Baseus", "Baseus Car Phone Holder Dashboard", 129, { sale: "auto", colors: ["Black"] }],
  ["phone-holders", "Oraimo", "Oraimo Car Phone Mount", 89, { colors: ["Black", "Blue"] }],
  ["phone-holders", "Awei", "Awei Car Phone Holder", 49, { sale: "auto", colors: ["Black"] }],
  ["phone-holders", "ESR", "ESR MagSafe Car Mount", 249, { colors: ["Black"] }],
  ["phone-holders", "Nillkin", "Nillkin Desk Phone Stand", 79, { colors: ["Black", "White"] }],
  ["phone-holders", "Spigen", "Spigen Klasden Desk Mount", 199, { colors: ["Black"] }],
  ["phone-holders", "UAG", "UAG Strapstand Phone Holder", 199, { sale: "auto", colors: ["Black", "Blue"] }],
  ["phone-holders", "Lamicall", "Lamicall Bike Phone Mount", 169, { colors: ["Black"] }],
  ["phone-holders", "Baseus", "Baseus Magnetic Phone Stand for Desk", 99, { colors: ["Black", "White"] }],
  ["phone-holders", "Oraimo", "Oraimo 360 Rotating Phone Ring Holder", 39, { sale: "auto", colors: ["Black", "Blue", "Pink"] }],

  // ============ Car Chargers ============
  ["car-chargers", "Anker", "Anker 321 Car Charger 36W 2-Port", 199, { sale: "auto", colors: ["Black"] }],
  ["car-chargers", "Anker", "Anker 523 Car Charger 65W USB-C", 449, { colors: ["Black"] }],
  ["car-chargers", "Baseus", "Baseus 100W Car Charger 4-Port", 299, { sale: "auto", colors: ["Black"] }],
  ["car-chargers", "Oraimo", "Oraimo 25W Car Charger Dual USB", 99, { colors: ["Black", "White"] }],
  ["car-chargers", "Awei", "Awei 2-Port Car Charger 24W", 49, { sale: "auto", colors: ["Black"] }],
  ["car-chargers", "Belkin", "Belkin 48W Car Charger Dual USB-C", 349, { colors: ["Black"] }],
  ["car-chargers", "UGREEN", "UGREEN 30W USB-C Car Charger", 149, { colors: ["Black"] }],
  ["car-chargers", "Samsung", "Samsung 25W Car Charger", 199, { colors: ["Black"] }],
  ["car-chargers", "Nillkin", "Nillkin 25W Car Charger", 89, { colors: ["Black", "White"] }],
  ["car-chargers", "Xiaomi", "Xiaomi 100W Car Charger", 299, { sale: "auto", colors: ["Black"] }],
  ["car-chargers", "Oraimo", "Oraimo 40W Car Charger Type-C", 129, { colors: ["Black"] }],
  ["car-chargers", "Awei", "Awei 36W Car Charger 3-Port", 59, { colors: ["Black"] }],

  // ============ Bluetooth Adapters ============
  ["bluetooth-adapters", "UGREEN", "UGREEN Bluetooth 5.0 USB Adapter", 149, { sale: "auto", colors: ["Black"] }],
  ["bluetooth-adapters", "TP-Link", "TP-Link UB400 Bluetooth 4.0 USB Adapter", 99, { colors: ["Black", "White"] }],
  ["bluetooth-adapters", "Baseus", "Baseus Bluetooth 5.3 Audio Adapter", 199, { colors: ["Black"] }],
  ["bluetooth-adapters", "Awei", "Awei Bluetooth 5.0 Car Adapter AUX", 129, { sale: "auto", colors: ["Black"] }],
  ["bluetooth-adapters", "Oraimo", "Oraimo Bluetooth Car Kit FM Transmitter", 149, { colors: ["Black"] }],
  ["bluetooth-adapters", "Belkin", "Belkin AUX Bluetooth Adapter", 299, { colors: ["Black", "White"] }],
  ["bluetooth-adapters", "ESR", "ESR Bluetooth 5.3 Receiver", 179, { colors: ["Black"] }],
  ["bluetooth-adapters", "Nillkin", "Nillkin Bluetooth 5.3 AUX Adapter", 129, { colors: ["Black"] }],

  // ============ Tablet Cases ============
  ["tablet-cases", "Samsung", "Samsung Smart Book Cover for Galaxy Tab A9+", 249, { sale: "auto", colors: ["Black", "Navy"] }],
  ["tablet-cases", "Samsung", "Samsung Book Cover for Galaxy Tab S9 FE", 399, { colors: ["Black", "Beige"] }],
  ["tablet-cases", "Oraimo", "Oraimo Tablet Case for Lenovo Tab M10", 99, { colors: ["Black", "Blue"] }],
  ["tablet-cases", "Awei", "Awei Folio Case for 10 inch Tablet", 89, { sale: "auto", colors: ["Black", "Blue", "Pink"] }],
  ["tablet-cases", "Baseus", "Baseus Tablet Stand Case 10-11 inch", 149, { colors: ["Black", "Grey"] }],
  ["tablet-cases", "Apple", "Apple Smart Folio for iPad 10th Gen", 599, { colors: ["White", "Black", "Navy"] }],
  ["tablet-cases", "Apple", "Apple Smart Keyboard Folio for iPad Air", 1299, { colors: ["Black"] }],
  ["tablet-cases", "Nillkin", "Nillkin Tablet Folio Case for Redmi Pad SE", 129, { sale: "auto", colors: ["Black", "Blue"] }],
  ["tablet-cases", "Oraimo", "Oraimo Tablet Case for itel Pad 1", 79, { colors: ["Black", "Blue"] }],
  ["tablet-cases", "Spigen", "Spigen Rugged Case for iPad Mini 6", 299, { colors: ["Black", "Navy"] }],
  ["tablet-cases", "Lamicall", "Lamicall iPad Case with Pencil Holder", 199, { colors: ["Black", "Blue"] }],
  ["tablet-cases", "Baseus", "Baseus Magnetic Folio for iPad 10th Gen", 199, { sale: "auto", colors: ["Black", "White"] }],

  // ============ Tablet Accessories ============
  ["tablet-accessories", "Samsung", "Samsung S Pen Creator Edition", 299, { sale: "auto", colors: ["Black", "Beige"] }],
  ["tablet-accessories", "Apple", "Apple Pencil (1st Gen)", 999, { colors: ["White"] }],
  ["tablet-accessories", "Apple", "Apple Pencil Pro", 1299, { colors: ["White"] }],
  ["tablet-accessories", "Apple", "Apple Pencil (USB-C)", 749, { colors: ["White"] }],
  ["tablet-accessories", "Lamicall", "Lamicall Tablet Stand Adjustable Aluminium", 249, { sale: "auto", colors: ["Silver", "Black"] }],
  ["tablet-accessories", "Baseus", "Baseus Tablet Holder Bed Mount", 199, { colors: ["Black"] }],
  ["tablet-accessories", "Oraimo", "Oraimo Stylus Pen for Tablets", 149, { colors: ["Black", "White"] }],
  ["tablet-accessories", "UGREEN", "UGREEN Tablet Desk Stand Foldable", 179, { sale: "auto", colors: ["Black", "Grey"] }],
  ["tablet-accessories", "Awei", "Awei Capacitive Stylus Pen 2-in-1", 79, { colors: ["Black", "White"] }],
  ["tablet-accessories", "Spigen", "Spigen Tablet Stand Heavy-Duty", 299, { colors: ["Black"] }],
  ["tablet-accessories", "Apple", "Apple Magic Keyboard for iPad 10th Gen", 1499, { colors: ["White"] }],
  ["tablet-accessories", "Nillkin", "Nillkin Stylus Pen for iPad", 129, { sale: "auto", colors: ["Black", "White"] }],
];