// Demo catalogue — FASHION products.
// opts.sizes / opts.colors generate variants; opts.v explicit variants.

export const FASHION = [
  // ============ Men's Fashion ============
  ["t-shirts-polos", "ralph-lauren", "Men's Classic Fit Cotton Polo Shirt", 349,
    { sale: "auto", new: true, sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Navy", "White", "Black"] }],
  ["t-shirts-polos", "lacoste", "Men's Piqué Polo Shirt with Logo", 449,
    { sizes: ["S", "M", "L", "XL"], colors: ["White", "Navy"] }],
  ["t-shirts-polos", "gold-coast-apparel", "Premium Cotton Crew Neck T-Shirt", 149,
    { sale: "auto", new: true, sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "White", "Grey"] }],
  ["t-shirts-polos", "accra-threads", "Streetwear Oversized T-Shirt", 199,
    { new: true, sizes: ["M", "L", "XL", "XXL"], colors: ["White", "Sand", "Black"] }],
  ["t-shirts-polos", "accra-threads", "Essential Drop Shoulder Tee", 169,
    { sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey", "Olive"] }],
  ["shirts", "ralph-lauren", "Men's Slim Fit Formal Shirt", 399,
    { sale: "auto", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["White", "Light Blue"] }],
  ["shirts", "tommy-hilfiger", "Oxford Button-Down Casual Shirt", 459,
    { sizes: ["S", "M", "L", "XL"], colors: ["White", "Blue", "Pink"] }],
  ["shirts", "accra-threads", "Short-Sleeve Chambray Shirt", 329,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Denim Blue", "Grey"] }],
  ["shirts", "kente-co", "Kente Print Slim Fit Shirt", 549,
    { sale: "auto", new: true, sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Kente Gold", "Kente Black"] }],
  ["trousers-chinos", "dockers", "Dockers Classic Fit Chino Trousers", 399,
    { sale: "auto", sizes: ["30", "32", "34", "36", "38"], colors: ["Khaki", "Navy", "Black"] }],
  ["trousers-chinos", "dockers", "Slim Fit Stretch Chinos", 429,
    { sizes: ["30", "32", "34", "36"], colors: ["Beige", "Grey", "Olive"] }],
  ["trousers-chinos", "gold-coast-apparel", "Men's Pleated Formal Trousers", 349,
    { sizes: ["30", "32", "34", "36", "38"], colors: ["Black", "Charcoal"] }],
  ["trousers-chinos", "accra-threads", "Tapered Cargo Trousers", 319,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Olive", "Black", "Grey"] }],
  ["jeans", "levis", "Levi's 511 Slim Fit Jeans", 499,
    { sale: "auto", sizes: ["30", "32", "34", "36", "38"], colors: ["Rigid", "Mid Blue", "Black"] }],
  ["jeans", "levis", "Levi's 501 Original Fit Jeans", 549,
    { sizes: ["30", "32", "34", "36", "38"], colors: ["Mid Blue", "Light Blue"] }],
  ["jeans", "wrangler", "Wrangler Regular Fit Jeans", 399,
    { sizes: ["30", "32", "34", "36", "38"], colors: ["Blue", "Black"] }],
  ["jeans", "tema-denim-co", "Straight Leg Stretch Denim Jeans", 429,
    { sale: "auto", new: true, sizes: ["30", "32", "34", "36"], colors: ["Indigo", "Black", "Grey"] }],
  ["shorts", "nike", "Nike Dri-FIT Training Shorts", 249,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Navy", "Grey"] }],
  ["shorts", "accra-threads", "Men's Cargo Shorts Multi-Pocket", 229,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Khaki", "Olive", "Black"] }],
  ["shorts", "wrangler", "Wrangler Denim Shorts", 299,
    { sizes: ["30", "32", "34", "36"], colors: ["Blue", "Black"] }],
  ["mens-suits-blazers", "at-jabari", "Two-Piece Slim Fit Suit", 1499,
    { sale: "auto", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Charcoal", "Navy", "Black"] }],
  ["mens-suits-blazers", "kente-co", "Kente Accent Three-Piece Suit", 2599,
    { sizes: ["M", "L", "XL"], colors: ["Kente Gold"] }],
  ["mens-jackets-coats", "north-face", "Men's Lightweight Bomber Jacket", 699,
    { sale: "auto", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "Olive"] }],
  ["mens-jackets-coats", "levis", "Levi's Trucker Denim Jacket", 799,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Mid Blue", "Black"] }],
  ["underwear", "calvin-klein", "Calvin Klein Cotton Boxer Briefs 3-Pack", 449,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "White"] }],
  ["underwear", "calvin-klein", "Classic Trunks 3-Pack", 399,
    { sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey"] }],
  ["mens-sleepwear", "calvin-klein", "Cotton Pyjama Set with Shorts", 349,
    { sizes: ["M", "L", "XL"], colors: ["Navy", "Grey"] }],
  ["mens-sleepwear", "gold-coast-apparel", "Soft Jersey Loungewear Set", 329,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Charcoal", "Navy"] }],
  ["mens-sportswear", "nike", "Nike Dry Training T-Shirt", 249,
    { sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "White", "Red"] }],
  ["mens-sportswear", "adidas", "Adidas 3-Stripes Joggers", 449,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey"] }],
  ["mens-traditional-wear", "woodin", "Woodin Kente Agbada Set", 1899,
    { sale: "auto", new: true, sizes: ["M", "L", "XL", "XXL"], colors: ["Kente Gold"] }],
  ["mens-traditional-wear", "kente-co", "Kente Bow Tie & Pocket Square Set", 199,
    { new: true, colors: ["Kente Gold", "Kente Black"] }],
  ["mens-fashion-shoes", "skechers", "Skechers Men's Slip-Resistant Oxfords", 749,
    { sale: "auto", eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Brown"] }],
  ["mens-fashion-shoes", "clarks", "Clarks Men's Leather Derby Shoes", 999,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Tan"] }],
  ["mens-fashion-shoes", "bata", "Bata Men's Formal Lace-Up Shoes", 549,
    { eu: ["40", "41", "42", "43"], colors: ["Black", "Brown"] }],
  ["mens-fashion-shoes", "florsheim", "Men's Leather Loafers", 899,
    { sale: "auto", eu: ["40", "41", "42", "43", "44"], colors: ["Brown", "Black"] }],
  ["mens-fashion-sandals-slippers", "birkenstock", "Birkenstock Men's Leather Sandals", 899,
    { sale: "auto", eu: ["40", "41", "42", "43", "44"], colors: ["Brown", "Black"] }],
  ["mens-fashion-sandals-slippers", "crocs", "Crocs Classic Clog", 349,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Navy", "White"] }],
  ["mens-fashion-sandals-slippers", "bata", "Men's Comfort Flip Flops", 149,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Blue"] }],
  ["mens-fashion-bags", "herschel", "Herschel Classic Canvas Messenger Bag", 799,
    { sale: "auto", colors: ["Black", "Navy"] }],
  ["mens-fashion-bags", "fossil", "Fossil Men's Leather Briefcase", 1499,
    { colors: ["Brown", "Black"] }],
  ["mens-fashion-belts", "fossil", "Genuine Leather Belt with Buckle", 349,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Brown"] }],
  ["mens-fashion-belts", "guess", "Reversible Leather Belt", 329,
    { sizes: ["M", "L", "XL"], colors: ["Black/Brown"] }],
  ["mens-fashion-wallets", "fossil", "Fossil Men's Leather Wallet", 549,
    { sale: "auto", colors: ["Brown", "Black"] }],
  ["mens-fashion-wallets", "guess", "Slim Card Holder Wallet", 399,
    { colors: ["Black", "Brown"] }],
  ["mens-fashion-watches", "fossil", "Fossil Chronograph Watch Steel", 1799,
    { sale: "auto", colors: ["Silver", "Gold"] }],
  ["mens-fashion-watches", "guess", "Guess Men's Steel Watch", 1499,
    { colors: ["Silver", "Black"] }],
  ["mens-fashion-watches", "casio", "Casio Classic Digital Watch", 449,
    { new: true, colors: ["Black", "Silver"] }],
  ["mens-fashion-sunglasses", "ray-ban", "Ray-Ban Aviator Sunglasses", 1299,
    { sale: "auto", colors: ["Gold/Green", "Black"] }],
  ["mens-fashion-sunglasses", "oakley", "Oakley Polarized Sport Sunglasses", 1499,
    { colors: ["Black", "Matte Grey"] }],
  ["mens-fashion-hats-caps", "nike", "Nike Dri-FIT Baseball Cap", 199,
    { sale: "auto", colors: ["Black", "Navy", "Grey"] }],
  ["mens-fashion-hats-caps", "adidas", "Adidas Originals Cap", 219,
    { colors: ["Black", "White"] }],
  ["mens-accessories", "tommy-hilfiger", "Silk Tie & Cufflinks Set", 349,
    { colors: ["Navy", "Burgundy"] }],
  ["mens-accessories", "gold-coast-apparel", "Men's Ankle Socks 5-Pack", 129,
    { sale: "auto", colors: ["Black", "White"] }],

  // ============ Women's Fashion ============
  ["dresses", "minku", "Minku Kente Print Midi Dress", 699,
    { sale: "auto", new: true, sizes: ["S", "M", "L", "XL"], colors: ["Kente Gold", "Kente Green"] }],
  ["dresses", "zara", "Elegant Floral Wrap Dress", 599,
    { sizes: ["S", "M", "L", "XL"], colors: ["Multi Floral"] }],
  ["dresses", "minku", "A-Line Summer Midi Dress", 549,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Sage", "Coral", "Navy"] }],
  ["dresses", "minku", "Volta Vogue Off-Shoulder Dress", 649,
    { sizes: ["S", "M", "L", "XL"], colors: ["Yellow", "Pink"] }],
  ["dresses", "zara", "Pleated Fit-and-Flare Dress", 749,
    { sale: "auto", sizes: ["S", "M", "L"], colors: ["Blush", "Navy"] }],
  ["dresses", "minku", "Ghana Print Wrap Dress", 729,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Multi Print"] }],
  ["tops-blouses", "zara", "Satin Blouse with V-Neck", 399,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Blush", "Ivory", "Black"] }],
  ["tops-blouses", "forever21", "Off-Shoulder Ruffle Top", 299,
    { sizes: ["S", "M", "L"], colors: ["White", "Pink"] }],
  ["tops-blouses", "minku", "Print Peplum Blouse", 349,
    { sizes: ["S", "M", "L", "XL"], colors: ["Multi", "Black"] }],
  ["tops-blouses", "zara", "Classic Button-Up Blouse", 429,
    { sizes: ["S", "M", "L", "XL"], colors: ["White", "Light Blue"] }],
  ["t-shirts", "forever21", "Women's Essential Crew Tee", 149,
    { sizes: ["S", "M", "L", "XL"], colors: ["White", "Black", "Grey"] }],
  ["t-shirts", "nike", "Nike Women's Graphic Tee", 249,
    { sale: "auto", sizes: ["S", "M", "L"], colors: ["Black", "White"] }],
  ["t-shirts", "adidas", "Adidas Women's Logo Tee", 269,
    { sizes: ["S", "M", "L"], colors: ["White", "Pink"] }],
  ["skirts", "zara", "High-Waist Pencil Skirt", 499,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Beige"] }],
  ["skirts", "forever21", "Pleated Midi Skirt", 399,
    { sizes: ["S", "M", "L"], colors: ["Navy", "Burgundy"] }],
  ["skirts", "minku", "Wrap Mini Skirt with Print", 329,
    { new: true, sizes: ["S", "M", "L"], colors: ["Multi", "Black"] }],
  ["skirts", "zara", "Denim A-Line Skirt", 449,
    { sizes: ["S", "M", "L"], colors: ["Mid Blue"] }],
  ["trousers", "zara", "High-Waist Wide Leg Trousers", 549,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Beige"] }],
  ["trousers", "forever21", "Cropped Tailored Trousers", 429,
    { sizes: ["S", "M", "L"], colors: ["Charcoal", "Navy"] }],
  ["trousers", "minku", "Wax Print Palazzo Trousers", 449,
    { new: true, sizes: ["S", "M", "L", "XL"], colors: ["Multi", "Blue"] }],
  ["womens-fashion-jeans", "levis", "Levi's 721 High-Rise Skinny Jeans", 549,
    { sale: "auto", sizes: ["26", "28", "30", "32", "34"], colors: ["Mid Blue", "Black"] }],
  ["womens-fashion-jeans", "zara", "High-Waist Mom Jeans", 549,
    { sizes: ["26", "28", "30", "32"], colors: ["Light Blue", "Blue"] }],
  ["womens-fashion-jeans", "wrangler", "Wrangler Stretch Bootcut Jeans", 499,
    { sizes: ["26", "28", "30", "32", "34"], colors: ["Blue", "Grey"] }],
  ["womens-fashion-shorts", "forever21", "High-Rise Denim Shorts", 279,
    { sale: "auto", sizes: ["26", "28", "30", "32"], colors: ["Blue", "Black"] }],
  ["womens-fashion-shorts", "zara", "Linen Blend Casual Shorts", 349,
    { sizes: ["S", "M", "L"], colors: ["Beige", "White"] }],
  ["jumpsuits", "zara", "Wide Leg Jumpsuit", 799,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Olive"] }],
  ["jumpsuits", "forever21", "Sleeveless Romper", 429,
    { new: true, sizes: ["S", "M", "L"], colors: ["Floral", "Black"] }],
  ["womens-suits-blazers", "zara", "Women's Tailored Blazer", 899,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Beige"] }],
  ["womens-suits-blazers", "forever21", "Oversized Check Blazer", 749,
    { sizes: ["S", "M", "L"], colors: ["Grey Check"] }],
  ["womens-jackets-coats", "levis", "Levi's Women's Denim Jacket", 799,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Mid Blue", "Black"] }],
  ["womens-jackets-coats", "north-face", "Women's Lightweight Rain Jacket", 899,
    { sizes: ["S", "M", "L"], colors: ["Pink", "Navy"] }],
  ["underwear-lingerie", "calvin-klein", "Calvin Klein Women's Cotton Bralette", 349,
    { sale: "auto", sizes: ["S", "M", "L"], colors: ["Black", "White"] }],
  ["underwear-lingerie", "calvin-klein", "Women's Hipster Briefs 3-Pack", 449,
    { sizes: ["S", "M", "L", "XL"], colors: ["Black", "Beige"] }],
  ["womens-sleepwear", "forever21", "Satin Pyjama Set", 449,
    { sale: "auto", sizes: ["S", "M", "L"], colors: ["Blush", "Black"] }],
  ["womens-sleepwear", "zara", "Cotton Lounge Set", 399,
    { sizes: ["S", "M", "L"], colors: ["Grey", "Navy"] }],
  ["womens-sportswear", "nike", "Nike Women's Dri-FIT Leggings", 549,
    { sale: "auto", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey"] }],
  ["womens-sportswear", "adidas", "Adidas Women's Training Jacket", 649,
    { sizes: ["S", "M", "L"], colors: ["Black", "Blue"] }],
  ["womens-traditional-wear", "woodin", "Woodin Wax Print Wrap Dress", 949,
    { sale: "auto", new: true, sizes: ["S", "M", "L", "XL"], colors: ["Multi Print"] }],
  ["womens-traditional-wear", "gtp", "GTP Two-Piece Kaba & Slit Set", 1499,
    { sizes: ["M", "L", "XL"], colors: ["Multi Print"] }],
  ["womens-fashion-shoes", "nina", "Women's Block Heel Sandals", 649,
    { sale: "auto", eu: ["36", "37", "38", "39", "40"], colors: ["Black", "Nude"] }],
  ["womens-fashion-shoes", "skechers", "Skechers Women's Slip-On Sneakers", 749,
    { eu: ["36", "37", "38", "39", "40"], colors: ["White", "Black"] }],
  ["womens-fashion-shoes", "ninewest", "Women's Stiletto Heels", 899,
    { eu: ["36", "37", "38", "39"], colors: ["Black", "Red"] }],
  ["womens-fashion-shoes", "bata", "Bata Women's Mary Jane Shoes", 549,
    { eu: ["36", "37", "38", "39", "40"], colors: ["Black", "Brown"] }],
  ["womens-fashion-shoes", "nina", "Women's Ballet Flats", 449,
    { eu: ["36", "37", "38", "39", "40"], colors: ["Black", "Nude"] }],
  ["womens-fashion-sandals-slippers", "birkenstock", "Birkenstock Women's Arizona Sandals", 899,
    { eu: ["36", "37", "38", "39", "40"], colors: ["Brown", "Black"] }],
  ["womens-fashion-sandals-slippers", "crocs", "Crocs Women's Sandals", 299,
    { eu: ["36", "37", "38", "39"], colors: ["White", "Black", "Pink"] }],
  ["womens-fashion-sandals-slippers", "bata", "Women's Comfort Flip Flops", 139,
    { eu: ["36", "37", "38", "39", "40"], colors: ["Black", "Pink"] }],
  ["womens-fashion-sandals-slippers", "nina", "Women's Gladiator Sandals", 599,
    { eu: ["36", "37", "38", "39"], colors: ["Tan", "Black"] }],
  ["handbags", "michael-kors", "Michael Kors Jet Set Tote Bag", 2499,
    { new: true, colors: ["Black", "Brown", "Burgundy"] }],
  ["handbags", "guess", "Guess Crossbody Bag", 899,
    { colors: ["Black", "Gold"] }],
  ["handbags", "zara", "Structured Handbag", 649,
    { colors: ["Black", "Camel"] }],
  ["handbags", "zara", "Bucket Bag with Chain", 549,
    { colors: ["Black", "Beige"] }],
  ["handbags", "minku", "Kente Print Clutch Bag", 499,
    { new: true, colors: ["Kente Gold", "Kente Multi"] }],
  ["backpacks", "herschel", "Herschel Little America Backpack", 899,
    { colors: ["Black", "Navy"] }],
  ["backpacks", "jansport", "JanSport SuperBreak Backpack", 649,
    { colors: ["Black", "Pink", "Navy"] }],
  ["wallets-purses", "fossil", "Fossil Women's Leather Wallet", 549,
    { colors: ["Brown", "Black"] }],
  ["wallets-purses", "guess", "Guess Zip Around Wallet", 649,
    { colors: ["Black", "Gold"] }],
  ["womens-fashion-belts", "zara", "Faux Leather Belt Women", 249,
    { sizes: ["S", "M", "L"], colors: ["Black", "Brown"] }],
  ["womens-fashion-belts", "guess", "Chain Detail Belt", 349,
    { sizes: ["S", "M", "L"], colors: ["Gold", "Silver"] }],
  ["womens-fashion-watches", "fossil", "Fossil Women's Rose Gold Watch", 1799,
    { colors: ["Rose Gold", "Silver"] }],
  ["womens-fashion-watches", "guess", "Guess Women's Gold Watch", 1499,
    { colors: ["Gold", "Silver"] }],
  ["womens-fashion-sunglasses", "ray-ban", "Ray-Ban Round Sunglasses Women", 1199,
    { colors: ["Gold/Green", "Black"] }],
  ["womens-fashion-sunglasses", "guess", "Guess Cat-Eye Sunglasses", 849,
    { colors: ["Black", "Tortoise"] }],
  ["womens-fashion-hats-caps", "adidas", "Adidas Women's Cap", 199,
    { colors: ["Black", "White", "Pink"] }],
  ["womens-fashion-hats-caps", "zara", "Straw Sun Hat", 299,
    { colors: ["Natural", "Black"] }],
  ["womens-accessories", "swarovski", "Crystal Stud Earrings", 349,
    { colors: ["Silver", "Gold"] }],
  ["womens-accessories", "zara", "Silk Print Scarf", 249,
    { colors: ["Multi", "Navy"] }],
  ["womens-accessories", "minku", "Wax Print Headwrap", 129,
    { new: true, colors: ["Multi", "Gold"] }],

  // ============ Kids' Fashion ============
  ["boys-clothing", "carters", "Boys' Cotton Polo Shirt", 199,
    { sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"], colors: ["Navy", "Red", "Green"] }],
  ["boys-clothing", "carters", "Boys' Denim Jeans", 249,
    { sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"], colors: ["Blue", "Black"] }],
  ["boys-clothing", "carters", "Boys' Short Sleeve Shirt", 179,
    { sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"], colors: ["White", "Blue"] }],
  ["boys-clothing", "nike", "Nike Boys' Graphic T-Shirt", 179,
    { sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"], colors: ["Black", "Blue"] }],
  ["girls-clothing", "carters", "Girls' Floral Summer Dress", 229,
    { new: true, sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"], colors: ["Floral", "Pink"] }],
  ["girls-clothing", "carters", "Girls' Ruffle Top & Leggings Set", 219,
    { sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"], colors: ["Pink", "Purple"] }],
  ["girls-clothing", "minku", "Girls' Kente Print Dress", 299,
    { new: true, sizes: ["2-3Y", "4-5Y", "6-7Y"], colors: ["Kente Multi"] }],
  ["girls-clothing", "carters", "Girls' Skirt & Top Set", 239,
    { sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"], colors: ["Multi", "Peach"] }],
  ["baby-clothing", "carters", "Baby Bodysuit 3-Pack", 179,
    { sizes: ["0-3M", "3-6M", "6-12M"], colors: ["White", "Yellow"] }],
  ["baby-clothing", "carters", "Baby Romper with Footies", 219,
    { sizes: ["0-3M", "3-6M", "6-12M"], colors: ["Grey", "Blue"] }],
  ["baby-clothing", "minku", "Baby Kente Print Outfit Set", 349,
    { sizes: ["0-3M", "3-6M", "6-12M"], colors: ["Kente Multi"] }],
  ["school-wear", "carters", "School Uniform Shirt (Boys)", 199,
    { sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y", "12-13Y"], colors: ["White", "Blue"] }],
  ["school-wear", "carters", "School Pinafore Dress (Girls)", 229,
    { sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"], colors: ["Blue", "Green"] }],
  ["school-wear", "nike", "School Sports Shoes", 449,
    { eu: ["30", "32", "34", "36", "37"], colors: ["White", "Black"] }],
  ["childrens-shoes", "crocs", "Crocs Kids Classic Clog", 249,
    { eu: ["27", "28", "29", "30", "31"], colors: ["Black", "Pink", "Blue"] }],
  ["childrens-shoes", "nike", "Nike Kids' Running Shoes", 549,
    { eu: ["28", "29", "30", "31", "32", "33"], colors: ["Black", "Blue"] }],
  ["childrens-shoes", "carters", "Kids' School Shoes", 299,
    { eu: ["27", "28", "29", "30", "31"], colors: ["Black", "Brown"] }],
  ["kids-fashion-sandals-slippers", "crocs", "Crocs Kids' Sandals", 199,
    { eu: ["27", "28", "29", "30", "31"], colors: ["Blue", "Pink"] }],
  ["kids-fashion-sandals-slippers", "bata", "Kids' Flip Flops", 99,
    { eu: ["27", "28", "29", "30"], colors: ["Black", "Red"] }],
  ["baby-shoes", "carters", "Baby First Walkers Shoes", 249,
    { eu: ["18", "19", "20", "21"], colors: ["White", "Pink", "Blue"] }],
  ["baby-shoes", "carters", "Baby Sandals", 199,
    { eu: ["18", "19", "20", "21"], colors: ["Brown", "White"] }],
  ["childrens-bags", "jansport", "JanSport Kids' Mini Backpack", 449,
    { colors: ["Black", "Pink", "Blue"] }],
  ["childrens-bags", "carters", "Kids' Drawstring Sports Bag", 129,
    { colors: ["Black", "Red"] }],
  ["childrens-accessories", "carters", "Kids' Socks 5-Pack", 99,
    { colors: ["White", "Mixed"] }],
  ["childrens-accessories", "minku", "Kids' Kente Bow Headband", 79,
    { colors: ["Kente Multi"] }],

  // ============ Footwear ============
  ["mens-shoes", "nike", "Nike Air Force 1 Low Sneakers", 1499,
    { new: true, eu: ["40", "41", "42", "43", "44", "45"], colors: ["White", "Black"] }],
  ["mens-shoes", "adidas", "Adidas Superstar Sneakers", 1299,
    { eu: ["40", "41", "42", "43", "44"], colors: ["White", "Black"] }],
  ["mens-shoes", "puma", "Puma Suede Classic Sneakers", 999,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Red"] }],
  ["mens-shoes", "skechers", "Skechers Men's Walking Shoes", 899,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Grey"] }],
  ["womens-shoes", "nike", "Nike Air Max Women's Sneakers", 1699,
    { new: true, eu: ["36", "37", "38", "39", "40"], colors: ["White", "Pink"] }],
  ["womens-shoes", "adidas", "Adidas Stan Smith Women", 1199,
    { eu: ["36", "37", "38", "39", "40"], colors: ["White", "Green"] }],
  ["womens-shoes", "skechers", "Skechers Women's Walking Shoes", 849,
    { eu: ["36", "37", "38", "39", "40"], colors: ["White", "Pink"] }],
  ["womens-shoes", "converse", "Converse Chuck Taylor Women", 899,
    { eu: ["36", "37", "38", "39"], colors: ["White", "Black"] }],
  ["sneakers", "nike", "Nike Revolution Running Sneakers", 1099,
    { eu: ["40", "41", "42", "43", "44", "45"], colors: ["Black", "Blue"] }],
  ["sneakers", "adidas", "Adidas Lite Racer Sneakers", 999,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "White"] }],
  ["sneakers", "new-balance", "New Balance 237 Lifestyle Sneakers", 1099,
    { eu: ["40", "41", "42", "43", "44"], colors: ["White", "Cream"] }],
  ["sneakers", "skechers", "Skechers Uno Sneakers", 999,
    { new: true, eu: ["40", "41", "42", "43", "44"], colors: ["White", "Pink"] }],
  ["formal-shoes", "clarks", "Clarks Men's Formal Oxfords", 1249,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Brown"] }],
  ["formal-shoes", "florsheim", "Men's Cap-Toe Derby Shoes", 1099,
    { eu: ["41", "42", "43", "44"], colors: ["Black"] }],
  ["formal-shoes", "nina", "Women's Classic Pumps", 749,
    { eu: ["36", "37", "38", "39"], colors: ["Black", "Nude"] }],
  ["boots", "timberland", "Timberland 6-Inch Premium Boots", 2499,
    { eu: ["41", "42", "43", "44", "45"], colors: ["Wheat", "Black"] }],
  ["boots", "dr-martens", "Dr. Martens 1460 Boots", 2599,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Cherry"] }],
  ["sandals", "birkenstock", "Birkenstock Arizona Sandals", 949,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Brown", "Black"] }],
  ["sandals", "teva", "Teva Universal Sandals", 699,
    { eu: ["40", "41", "42", "43"], colors: ["Black", "Blue"] }],
  ["sandals", "crocs", "Crocs Men's Sandals", 349,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Khaki"] }],
  ["slippers", "crocs", "Crocs Classic Clogs", 329,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Navy", "White"] }],
  ["slippers", "bata", "Men's Indoor Slippers", 199,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Brown", "Black"] }],
  ["sports-shoes", "nike", "Nike Men's Running Shoes", 1299,
    { eu: ["40", "41", "42", "43", "44", "45"], colors: ["Black", "Red"] }],
  ["sports-shoes", "adidas", "Adidas Ultraboost Running", 1999,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "White"] }],
  ["sports-shoes", "puma", "Puma Football Cleats", 899,
    { eu: ["40", "41", "42", "43", "44"], colors: ["Black", "Green"] }],

  // ============ Fashion Accessories ============
  ["fashion-accessories-watches", "fossil", "Fossil Minimalist Watch", 1499,
    { colors: ["Silver", "Black"] }],
  ["fashion-accessories-watches", "casio", "Casio Edifice Watch", 1299,
    { colors: ["Silver", "Black"] }],
  ["fashion-accessories-sunglasses", "ray-ban", "Ray-Ban Wayfarer Sunglasses", 1249,
    { colors: ["Black", "Tortoise"] }],
  ["fashion-accessories-sunglasses", "oakley", "Oakley Holbrook Sunglasses", 1399,
    { colors: ["Black", "Matte"] }],
  ["jewelry", "swarovski", "Crystal Pendant Necklace", 449,
    { colors: ["Silver", "Gold"] }],
  ["jewelry", "swarovski", "Hoop Earrings 14K Gold Plated", 399,
    { new: true, colors: ["Gold", "Silver"] }],
  ["jewelry", "minku", "Beaded Waist Beads", 149,
    { colors: ["Multi", "Gold"] }],
  ["fashion-accessories-bags", "herschel", "Herschel Travel Duffle Bag", 1099,
    { colors: ["Black", "Navy"] }],
  ["fashion-accessories-bags", "jansport", "JanSport Large Backpack", 749,
    { colors: ["Black", "Blue"] }],
  ["fashion-accessories-bags", "zara", "Crossbody Phone Pouch", 349,
    { colors: ["Black", "Brown"] }],
  ["fashion-accessories-wallets", "fossil", "Fossil Card Holder", 449,
    { colors: ["Brown", "Black"] }],
  ["fashion-accessories-wallets", "guess", "Guess Coin Wallet", 499,
    { colors: ["Black", "Gold"] }],
  ["fashion-accessories-belts", "fossil", "Fossil Leather Belt", 449,
    { sizes: ["S", "M", "L", "XL"], colors: ["Black", "Brown"] }],
  ["fashion-accessories-belts", "guess", "Woven Leather Belt", 399,
    { sizes: ["S", "M", "L"], colors: ["Tan", "Black"] }],
  ["caps-hats", "nike", "Nike Heritage86 Cap", 199,
    { colors: ["Black", "Navy", "Grey"] }],
  ["caps-hats", "gold-coast-apparel", "Embroidered Kente Cap", 249,
    { new: true, colors: ["Kente Multi", "Black"] }],
  ["scarves", "zara", "Knit Winter Scarf", 249,
    { colors: ["Charcoal", "Burgundy"] }],
  ["scarves", "minku", "Silk Print Wrap Scarf", 299,
    { colors: ["Multi", "Gold"] }],
  ["fashion-accessories-hair-accessories", "minku", "Ankara Hair Bows Set", 99,
    { colors: ["Multi", "Gold"] }],
  ["fashion-accessories-hair-accessories", "zara", "Tortoise Hair Clips", 129,
    { colors: ["Tortoise", "Black"] }],
  ["travel-accessories", "herschel", "Herschel Pouch Set", 349,
    { colors: ["Black", "Navy"] }],
  ["travel-accessories", "jansport", "Packing Cubes Set of 3", 299,
    { colors: ["Black", "Grey"] }],

  // ============ Umbrella / level-2 fills ============
  ["fashion", "gold-coast-apparel", "Fashion Accessory Gift Set — Cap, Scarf & Belt", 549,
    { colors: ["Black"] }],
  ["mens-fashion", "kente-co", "Gentleman's Kente Accessory Bundle", 749,
    { colors: ["Kente Multi"] }],
  ["womens-fashion", "minku", "Women's Style Starter Set — Top, Scarf & Belt", 899,
    { colors: ["Multi"] }],
  ["kids-fashion", "carters", "Kids' Essentials Wardrobe Pack", 549,
    { sizes: ["4-5Y", "6-7Y", "8-9Y"], colors: ["Navy"] }],
  ["footwear", "crocs", "Comfort Footwear Duo — Clogs & Sandals", 649,
    { eu: ["40", "41", "42", "43"], colors: ["Black"] }],
  ["fashion-accessories", "fossil", "Accessories Gift Box — Wallet & Belt", 949,
    { colors: ["Brown"] }],
];