// Demo catalogue brand data for Yemanuel Store.
// Exported for use by generate-demo-catalogue.mjs

export const BRANDS = [
  // ---------- Electronics (global) ----------
  ["Samsung", "samsung", "Global leader in smartphones, TVs, home appliances and memory technology, trusted across Ghana for dependable electronics."],
  ["Apple", "apple", "Premium iPhones, iPads, MacBooks and accessories known for refined design, longevity and resale value."],
  ["Huawei", "huawei", "Flagship smartphones, tablets, wearables and networking gear engineered for performance."],
  ["Xiaomi", "xiaomi", "Popular value-for-money smartphones, wearables, TVs and smart home devices."],
  ["Tecno", "tecno", "Mobile-first brand delivering cameras, batteries and features tuned for the African market."],
  ["Infinix", "infinix", "Youth-focused smartphones and accessories with big batteries and sharp displays."],
  ["itel", "itel", "Affordable, dependable smartphones and feature phones built for everyday use."],
  ["Nokia", "nokia", "Iconic phones with classic reliability and long battery life."],
  ["Sony", "sony", "Premium audio, cameras, televisions and PlayStation gaming hardware."],
  ["LG", "lg", "Innovative home appliances, televisions, audio and mobile accessories."],
  ["Hisense", "hisense", "Smart TVs, refrigerators and appliances offering strong value for Ghanaian homes."],
  ["TCL", "tcl", "Large-screen smart televisions and quality displays at accessible prices."],
  ["HP", "hp", "Laptops, desktops, monitors and printing solutions for home and business."],
  ["Dell", "dell", "Business and personal computers, monitors and accessories with robust build quality."],
  ["Lenovo", "lenovo", "ThinkPad, IdeaPad and Legion computers plus tablets and accessories."],
  ["Acer", "acer", "Affordable laptops, desktops and monitors for students and professionals."],
  ["JBL", "jbl", "Portable Bluetooth speakers, headphones and soundbars with punchy sound."],
  ["Anker", "anker", "Chargers, power banks, cables and audio accessories engineered for reliability."],
  ["Baseus", "baseus", "Modern charging and accessory gear with clean design and fast performance."],
  ["Oraimo", "oraimo", "Everyday tech accessories — earbuds, chargers, power banks and cables — made for real life."],
  ["Bose", "bose", "Premium headphones, speakers and soundbars known for noise cancellation."],
  ["Sennheiser", "sennheiser", "German-engineered audio for creators, gamers and music lovers."],
  ["Logitech", "logitech", "Keyboards, mice, webcams and gaming peripherals trusted worldwide."],
  ["Razer", "razer", "Gaming mice, keyboards, headsets and accessories with pro-grade performance."],
  ["SanDisk", "sandisk", "Memory cards and storage you can rely on for photos, video and files."],
  ["Kingston", "kingston", "Memory, storage and SSDs delivering dependable capacity and speed."],
  ["TP-Link", "tp-link", "Wi-Fi routers, extenders, switches and smart home devices."],
  ["Netgear", "netgear", "Networking hardware for homes and small offices."],
  ["ZTE", "zte", "Telecom equipment, 4G routers and mobile devices."],
  ["Epson", "epson", "Projectors and printers delivering clear, dependable output."],
  ["Canon", "canon", "Cameras, lenses and imaging gear for enthusiasts and creators."],
  ["GoPro", "gopro", "Rugged action cameras built for adventure and travel."],
  ["Amazfit", "amazfit", "Smartwatches and fitness bands with excellent battery life."],
  ["Hikvision", "hikvision", "Global leader in security cameras and CCTV systems."],
  ["EZVIZ", "ezviz", "Smart home cameras and security solutions for peace of mind."],
  ["APC", "apc", "Back-UPS, surge protection and power protection solutions."],
  ["Skyworth", "skyworth", "Smart televisions with modern panels at friendly prices."],
  ["Amazon", "amazon", "Echo smart speakers and streaming devices that put Alexa at home."],
  ["Google", "google", "Nest smart speakers, streaming and smart home devices."],
  ["Roku", "roku", "Simple, fast streaming sticks and players for every TV."],
  ["Felicity", "felicity", "Solar inverters and battery storage systems for Ghanaian homes and businesses."],
  ["Luminous", "luminous", "Inverters and power backup solutions for uninterrupted electricity."],
  ["Fifine", "fifine", "USB microphones and podcasting gear for creators on a budget."],
  ["Mantel", "mantel", "Everyday electrical accessories, bulbs and power strips for Ghanaian homes."],

  // ---------- Fashion ----------
  ["Nike", "nike", "Global sportswear brand with performance shoes, apparel and training gear."],
  ["Adidas", "adidas", "Sportswear, sneakers and lifestyle apparel with iconic three-stripe style."],
  ["Puma", "puma", "Sport and lifestyle sneakers, apparel and accessories."],
  ["Levi's", "levis", "Legendary denim jeans and casual wear since 1853."],
  ["Wrangler", "wrangler", "Durable jeans, shirts and casual apparel for everyday wear."],
  ["Ralph Lauren", "ralph-lauren", "Classic American polo shirts and refined menswear."],
  ["Lacoste", "lacoste", "Sporty-chic polos, apparel and footwear with the crocodile crest."],
  ["Skechers", "skechers", "Comfort-first casual sneakers and walking shoes."],
  ["Converse", "converse", "Iconic canvas sneakers and streetwear classics."],
  ["Crocs", "crocs", "Lightweight, breathable clogs and sandals for everyday comfort."],
  ["Timberland", "timberland", "Durable boots and outdoor-inspired footwear."],
  ["Woodin", "woodin", "Iconic wax-print fabric house creating bold, colourful fashion for Africa."],
  ["GTP", "gtp", "Ghana's heritage textile brand famous for quality wax prints and fashion."],
  ["Minku", "minku", "Ghanaian womenswear brand known for vibrant, contemporary designs."],
  ["Kente & Co", "kente-co", "Authentic kente-inspired clothing and accessories made in Ghana."],
  ["Gold Coast Apparel", "gold-coast-apparel", "Casual clothing brand with a distinctly Ghanaian voice."],
  ["Accra Threads", "accra-threads", "Modern everyday apparel and streetwear designed in Accra."],

  // ---------- Cosmetics & Beauty ----------
  ["L'Oréal Paris", "loreal-paris", "Global beauty brand with hair, skin and makeup icons for every woman."],
  ["Maybelline New York", "maybelline-new-york", "Accessible, innovative makeup from mascara to foundation."],
  ["Nivea", "nivea", "Trusted skincare and body care for the whole family."],
  ["Neutrogena", "neutrogena", "Dermatologist-recommended skincare for healthy-looking skin."],
  ["CeraVe", "cerave", "Skincare developed with dermatologists, featuring essential ceramides."],
  ["Cetaphil", "cetaphil", "Gentle, clinically proven skincare for sensitive skin."],
  ["Garnier", "garnier", "Natural-inspired skincare and hair care at accessible prices."],
  ["Dove", "dove", "Gentle body washes, soaps and care products for real beauty."],
  ["Vaseline", "vaseline", "Body lotions and petroleum jelly for lasting skin nourishment."],
  ["Pantene", "pantene", "Pro-V hair care known for strong, shiny hair."],
  ["SheaMoisture", "sheamoisture", "Nourishing hair and body care powered by raw shea butter."],
  ["Mielle", "mielle", "Natural hair care crafted for textured, coily and curly hair."],
  ["Dark & Lovely", "dark-lovely", "Relaxers, hair colour and care for beautiful black hair."],
  ["Dudu Osun", "dudu-osun", "African black soap and natural skincare rooted in African tradition."],
  ["Huda Beauty", "huda-beauty", "High-pigment makeup and false lashes loved by beauty lovers worldwide."],
  ["Fenty Beauty", "fenty-beauty", "Makeup made for everyone, famous for its inclusive shade ranges."],
  ["MAC", "mac", "Professional makeup with rich colour and universal appeal."],
  ["NYX Professional Makeup", "nyx-professional-makeup", "Vibrant, cruelty-free makeup with pro-quality payoff."],
  ["La Roche-Posay", "la-roche-posay", "Dermatologist-recommended skincare for sensitive, reactive skin."],
  ["Gillette", "gillette", "Razors and shaving care engineered for the best shave."],
  ["Philips", "philips", "Grooming, shaving, hair and personal care appliances."],
  ["Remington", "remington", "Affordable hair dryers, straighteners and grooming tools."],
  ["Braun", "braun", "Precision shavers and grooming devices with German engineering."],

  // ---------- Home, Living & Appliances ----------
  ["Kenwood", "kenwood", "Kitchen machines and appliances for the home cook."],
  ["YEM", "yem", "Ghanaian household appliance brand built for local conditions."],
  ["Royal", "royal", "Affordable home appliances for the Ghanaian market."],
  ["Dyson", "dyson", "Innovative vacuums, hair tools and air technology."],
  ["Honeywell", "honeywell", "Fans, heaters and air quality solutions for the home."],
  ["Brother", "brother", "Sewing machines, printers and labelling solutions."],
  ["Pyrex", "pyrex", "Temper-proof glass bakeware and food storage."],
  ["Tupperware", "tupperware", "Airtight food storage for the modern kitchen."],
  ["Scotch-Brite", "scotch-brite", "Scouring pads and cleaning essentials."],
  ["OMO", "omo", "Laundry detergents trusted for tough stain removal."],
  ["Sharp", "sharp", "Televisions and appliances with trusted quality."],
  ["Eaton", "eaton", "Power protection, surge and backup solutions."],
  ["Microsoft", "microsoft", "Surface devices, accessories and software."],
  ["Skullcandy", "skullcandy", "Playful, bass-heavy audio for everyday life."],
  ["HyperX", "hyperx", "Gaming headsets, keyboards and esports gear."],

  // ---------- Fashion & Footwear (added) ----------
  ["At Jabari", "at-jabari", "Accra-born designer label crafting sharp, modern African tailoring."],
  ["Bata", "bata", "Everyday footwear with a century of shoemaking heritage."],
  ["Birkenstock", "birkenstock", "Contoured, comfortable sandals and footwear with timeless appeal."],
  ["Calvin Klein", "calvin-klein", "Minimalist, iconic fashion, underwear and accessories."],
  ["Carter's", "carters", "Trusted baby and kids clothing with soft comfort."],
  ["Clarks", "clarks", "Comfortable, quality footwear for men and women."],
  ["Dockers", "dockers", "Smart-casual chinos and trousers with a clean cut."],
  ["Dr. Martens", "dr-martens", "Rebellious, hardwearing boots and shoes with air-cushioned soles."],
  ["Florsheim", "florsheim", "Classic dress shoes and loafers for men."],
  ["Forever 21", "forever21", "Trend-led fast fashion for women and men."],
  ["Fossil", "fossil", "American heritage watches, bags and accessories."],
  ["Guess", "guess", "Denim, watches and accessories with iconic branding."],
  ["Herschel", "herschel", "Classic backpacks and travel accessories."],
  ["JanSport", "jansport", "Durable student backpacks and daypacks."],
  ["Michael Kors", "michael-kors", "Jet-set luxury handbags, watches and accessories."],
  ["New Balance", "new-balance", "Performance and lifestyle sneakers built for comfort."],
  ["Nina", "nina", "Women's dress shoes, sandals and heels."],
  ["Nine West", "ninewest", "Fashionable women's footwear and accessories."],
  ["The North Face", "north-face", "Outdoor jackets, backpacks and performance gear."],
  ["Oakley", "oakley", "Performance sunglasses and eyewear."],
  ["Ray-Ban", "ray-ban", "Legendary sunglasses with iconic frame styles."],
  ["Swarovski", "swarovski", "Crystal jewelry and accessories."],
  ["Tema Denim Co.", "tema-denim-co", "Ghanaian denim and casual wear cut in Tema."],
  ["Teva", "teva", "Adventure sandals built for water and trail."],
  ["Tommy Hilfiger", "tommy-hilfiger", "Classic American prep fashion and accessories."],
  ["Zara", "zara", "Fast fashion staples for women and men."],

  // ---------- Cosmetics, Beauty & Fragrance (added) ----------
  ["Always", "always", "Feminine care and personal hygiene trusted by women."],
  ["Axe", "axe", "Bold body sprays and grooming for confident men."],
  ["Beautyblender", "beauty-blender", "Original makeup sponges for a flawless, seamless finish."],
  ["Cantu", "cantu", "Shea butter hair care for naturally textured hair."],
  ["Carolina Herrera", "carolina-herrera", "Elegant designer fragrances and fashion."],
  ["Casio", "casio", "Reliable digital and analog watches with classic appeal."],
  ["Chanel", "chanel", "Iconic French luxury fashion and fragrances."],
  ["Colgate", "colgate", "Oral care products trusted by families worldwide."],
  ["Dior", "dior", "Haute couture fashion, beauty and signature fragrances."],
  ["Dolce & Gabbana", "dolce-gabbana", "Italian luxury fashion and iconic fragrances."],
  ["Foreo", "foreo", "Silicon facial cleansing and beauty devices."],
  ["Got2b", "got2b", "Styling gels, glues and sprays for bold hair looks."],
  ["Jo Malone", "jo-malone", "Refined British colognes and home scents."],
  ["NARS", "nars", "Pro-grade makeup and iconic shades."],
  ["Oral-B", "oral-b", "Electric toothbrushes and oral care products."],
  ["Real Techniques", "real-techniques", "Creator-designed makeup brushes and tools."],
  ["Scholl", "scholl", "Foot care and comfort products."],
  ["Sensations", "sensations", "Wigs and hair extensions in natural styles."],
  ["Thayers", "thayers", "Witch hazel toners and natural skincare."],
  ["The Ordinary", "the-ordinary", "Clinical skincare with honest formulas."],
  ["Tom Ford", "tom-ford", "Luxury fashion and sensual signature fragrances."],
  ["Victoria's Secret", "victorias-secret", "Lingerie, beauty and body mists."],
  ["Wahl", "wahl", "Professional and home hair clippers and trimmers."],
  ["X-Pression", "x-pression", "Braiding hair and extensions for protective styles."],

  // ---------- Yemanuel Store private label ----------
  ["Yemanuel Home", "yemanuel-home", "Yemanuel Store private-label home, kitchen and living."],
  ["Yemanuel Beauty", "yemanuel-beauty", "Yemanuel Store private-label beauty and self-care."],
  ["Yemanuel Fragrance", "yemanuel-fragrance", "Yemanuel Store private-label fragrance oils and mists."],
  ["Yemanuel Grooming", "yemanuel-grooming", "Yemanuel Store private-label men's grooming."],
  ["Binatone", "binatone", "Practical small appliances for the modern household."],
];