// Demo catalogue — HOME & LIVING products.

export const HOME = [
  // ============ Kitchen & Dining ============
  ["cookware", "yemanuel-home", "Non-Stick Cookware Set 10-Piece", 899,
    { sale: "auto", v: [{ n: "10-Piece", o: { Pack: "10" }, d: 0 }] }],
  ["cookware", "yemanuel-home", "Cast Iron Frying Pan 26cm", 349,
    { v: [{ n: "26cm", o: { Size: "26cm" }, d: 0 }] }],
  ["cookware", "yemanuel-home", "Ceramic Coated Saucepan 20cm", 249,
    { sale: "auto", v: [{ n: "20cm", o: { Size: "20cm" }, d: 0 }] }],
  ["cookware", "pyrex", "Pyrex Glass Baking Dish 3-Piece", 299,
    { sale: "auto", v: [{ n: "Set", o: {} , d: 0 }] }],
  ["cutlery", "yemanuel-home", "Stainless Steel Knife Set 8-Piece", 449,
    { sale: "auto", v: [{ n: "8-Piece", o: { Pack: "8" }, d: 0 }] }],
  ["kitchen-utensils", "yemanuel-home", "Silicone Kitchen Utensil Set 12-Piece", 249,
    { sale: "auto", v: [{ n: "12-Piece", o: { Pack: "12" }, d: 0 }] }],
  ["food-storage", "tupperware", "Tupperware Airtight Food Storage Set 6-Piece", 399,
    { sale: "auto", v: [{ n: "6-Piece", o: { Pack: "6" }, d: 0 }] }],
  ["food-storage", "yemanuel-home", "Glass Storage Containers with Lids 4-Pack", 299,
    { v: [{ n: "4-Pack", o: { Pack: "4" }, d: 0 }] }],
  ["kitchen-utensils", "yemanuel-home", "Stainless Steel Colander Set 2-Piece", 149,
    { sale: "auto", v: [{ n: "Set", o: {} , d: 0 }] }],
  ["dinnerware", "yemanuel-home", "Ceramic Dinner Set 16-Piece", 699,
    { sale: "auto", v: [{ n: "16-Piece", o: { Pack: "16" }, d: 0 }] }],
  ["dinnerware", "yemanuel-home", "Melamine Dinner Plates Set 12-Piece", 249,
    { v: [{ n: "12-Piece", o: { Pack: "12" }, d: 0 }] }],
  ["kitchen-utensils", "yemanuel-home", "Apron & Oven Mitt Set", 149,
    { sale: "auto", colors: ["Grey", "Teal"] }],

  // ============ Small Appliances ============
  ["blenders", "kenwood", "Kenwood Blender 1.5L 800W", 649,
    { sale: "auto", new: true, v: [{ n: "1.5L", o: { Size: "1.5L" }, d: 0 }] }],
  ["blenders", "binatone", "Binatone Smoothie Blender 2L", 449,
    { v: [{ n: "2L", o: { Size: "2L" }, d: 0 }] }],
  ["kitchen-appliances", "kenwood", "Kenwood Slow Juicer 800W", 1899,
    { sale: "auto", v: [{ n: "800W", o: {} , d: 0 }] }],
  ["kitchen-appliances", "royal", "Royal Multi-Fruit Juicer 500W", 899,
    { v: [{ n: "500W", o: {} , d: 0 }] }],
  ["kitchen-appliances", "kenwood", "Kenwood Hand Mixer 450W", 499,
    { sale: "auto", v: [{ n: "450W", o: {} , d: 0 }] }],
  ["electric-kettles", "kenwood", "Kenwood Electric Kettle 1.7L 2200W", 349,
    { sale: "auto", colors: ["Black", "Steel"] }],
  ["electric-kettles", "binatone", "Binatone Stainless Kettle 1.8L", 299,
    { colors: ["Steel"] }],
  ["kitchen-appliances", "kenwood", "Kenwood 2-Slice Toaster", 349,
    { sale: "auto", colors: ["Black", "White"] }],
  ["kitchen-appliances", "kenwood", "Kenwood Drip Coffee Maker 1.5L", 899,
    { v: [{ n: "1.5L", o: { Size: "1.5L" }, d: 0 }] }],
  ["kitchen-appliances", "royal", "Espresso Machine 15 Bar", 2499,
    { sale: "auto", v: [{ n: "15 Bar", o: {} , d: 0 }] }],
  ["electric-kettles", "royal", "Royal Travel Kettle 0.6L", 199,
    { v: [{ n: "0.6L", o: { Size: "0.6L" }, d: 0 }] }],
  ["kitchen-appliances", "kenwood", "Kenwood Food Processor 1000W", 1899,
    { sale: "auto", v: [{ n: "1000W", o: {} , d: 0 }] }],
  ["kitchen-appliances", "kenwood", "Kenwood Digital Air Fryer 5.5L", 1999,
    { sale: "auto", new: true, v: [{ n: "5.5L", o: { Size: "5.5L" }, d: 0 }] }],
  ["kitchen-appliances", "royal", "Royal Air Fryer 4.2L", 1499,
    { v: [{ n: "4.2L", o: { Size: "4.2L" }, d: 0 }] }],
  ["kitchen-appliances", "yem", "YEM Electric Grill & Griddle 2400W", 1299,
    { sale: "auto", v: [{ n: "2400W", o: {} , d: 0 }] }],
  ["kitchen-appliances", "yem", "YEM Electric Oven 45L 2500W", 3499,
    { sale: "auto", v: [{ n: "45L", o: { Size: "45L" }, d: 0 }] }],
  ["rice-cookers", "yem", "YEM Rice Cooker 1.8L", 699,
    { sale: "auto", v: [{ n: "1.8L", o: { Size: "1.8L" }, d: 0 }] }],
  ["kitchen-appliances", "binatone", "Binatone Sandwich Maker 700W", 399,
    { sale: "auto", colors: ["Black"] }],

  // ============ Appliances ============
  ["refrigerators", "hisense", "Hisense 260L Single Door Fridge", 5999,
    { sale: "auto", v: [{ n: "260L", o: { Size: "260L" }, d: 0 }] }],
  ["refrigerators", "lg", "LG 525L Double Door Side-by-Side Fridge", 15999,
    { v: [{ n: "525L", o: { Size: "525L" }, d: 0 }] }],
  ["washing-machines", "hisense", "Hisense 7kg Front Load Washer", 7999,
    { sale: "auto", v: [{ n: "7kg", o: { Size: "7kg" }, d: 0 }] }],
  ["washing-machines", "lg", "LG 6kg Twin Tub Washing Machine", 4499,
    { v: [{ n: "6kg", o: { Size: "6kg" }, d: 0 }] }],
  ["microwaves", "lg", "LG Microwave 20L Solo", 1499,
    { sale: "auto", v: [{ n: "20L", o: { Size: "20L" }, d: 0 }] }],
  ["microwaves", "hisense", "Hisense Microwave Grill 25L", 1799,
    { v: [{ n: "25L", o: { Size: "25L" }, d: 0 }] }],
  ["irons", "yem", "YEM Steam Iron 2000W", 249,
    { sale: "auto", colors: ["Blue", "White"] }],
  ["cleaning-household", "dyson", "Dyson V8 Cordless Vacuum Cleaner", 12999,
    { sale: "auto", colors: ["Iron", "Nickel"] }],
  ["fans", "honeywell", "Honeywell Stand Fan 16 inch 3-Speed", 599,
    { sale: "auto", colors: ["Black"] }],
  ["air-conditioners", "lg", "LG 1.5HP Inverter Split AC", 12999,
    { sale: "auto", v: [{ n: "1.5HP", o: {} , d: 0 }] }],
  ["air-conditioners", "hisense", "Hisense 1HP Split Air Conditioner", 9999,
    { v: [{ n: "1HP", o: {} , d: 0 }] }],
  ["freezers", "hisense", "Hisense 300L Double Door Freezer", 5999,
    { v: [{ n: "300L", o: { Size: "300L" }, d: 0 }] }],
  ["home-appliances", "yem", "YEM Instant Water Heater 3kW", 899,
    { sale: "auto", v: [{ n: "3kW", o: {} , d: 0 }] }],
  ["home-appliances", "brother", "Brother Sewing Machine 14-Stitch", 3499,
    { v: [{ n: "14-Stitch", o: {} , d: 0 }] }],

  // ============ Furniture ============
  ["sofas", "yemanuel-home", "3-Seater Fabric Sofa Grey", 9999,
    { sale: "auto", colors: ["Grey", "Beige"] }],
  ["sofas", "yemanuel-home", "Leather Look Recliner Sofa", 12999,
    { colors: ["Brown", "Black"] }],
  ["sofas", "yemanuel-home", "Accent Armchair with Wooden Legs", 3999,
    { sale: "auto", colors: ["Mustard", "Grey"] }],
  ["tables", "yemanuel-home", "Wooden Coffee Table with Storage", 1999,
    { colors: ["Walnut", "Black"] }],
  ["tables", "yemanuel-home", "6-Seater Dining Table Set", 7999,
    { sale: "auto", v: [{ n: "6-Seater", o: {} , d: 0 }] }],
  ["chairs", "yemanuel-home", "Dining Chair Upholstered Set of 4", 3499,
    { colors: ["Grey", "Beige"] }],
  ["beds", "yemanuel-home", "King Size Bed Frame with Headboard", 6999,
    { v: [{ n: "King", o: { Size: "King" }, d: 0 }] }],
  ["beds", "yemanuel-home", "Queen Size Bed Frame", 5499,
    { v: [{ n: "Queen", o: { Size: "Queen" }, d: 0 }] }],
  ["mattresses", "yemanuel-home", "Memory Foam Mattress 6 inch Queen", 4999,
    { v: [{ n: "Queen", o: { Size: "Queen" }, d: 0 }] }],
  ["mattresses", "yemanuel-home", "Pocket Spring Mattress King Size", 6999,
    { v: [{ n: "King", o: { Size: "King" }, d: 0 }] }],
  ["storage", "yemanuel-home", "2-Door Wardrobe with Mirror", 4499,
    { v: [{ n: "2-Door", o: {} , d: 0 }] }],
  ["tables", "yemanuel-home", "Dressing Table with Mirror & Stool", 2999,
    { v: [{ n: "Single", o: {} , d: 0 }] }],
  ["shelving", "yemanuel-home", "5-Tier Bookcase Open Shelf", 2499,
    { v: [{ n: "5-Tier", o: {} , d: 0 }] }],
  ["tables", "yemanuel-home", "Computer Desk with Drawer", 1899,
    { v: [{ n: "120cm", o: { Size: "120cm" }, d: 0 }] }],
  ["tables", "yemanuel-home", "Adjustable Standing Desk", 3999,
    { v: [{ n: "Standing", o: {} , d: 0 }] }],
  ["chairs", "yemanuel-home", "Ergonomic Office Chair with Lumbar Support", 2499,
    { colors: ["Black"] }],
  ["storage", "yemanuel-home", "TV Stand Media Console 140cm", 2999,
    { v: [{ n: "140cm", o: { Size: "140cm" }, d: 0 }] }],
  ["storage", "yemanuel-home", "3-Tier Shoe Rack", 499,
    { v: [{ n: "3-Tier", o: {} , d: 0 }] }],
  ["tables", "yemanuel-home", "Bedside Table Nightstand", 899,
    { v: [{ n: "Single", o: {} , d: 0 }] }],
  ["storage", "yemanuel-home", "4-Drawer Chest of Drawers", 2499,
    { v: [{ n: "4-Drawer", o: {} , d: 0 }] }],
  ["storage", "yemanuel-home", "Kids Study Desk with Chair", 1499,
    { colors: ["Pink", "Blue"] }],
  ["tables", "yemanuel-home", "Outdoor Rattan Chair with Cushion", 2999,
    { colors: ["Natural"] }],

  // ============ Bedding ============
  ["home-decor", "yemanuel-home", "100% Cotton Bed Sheet Set King", 599,
    { colors: ["White", "Blue", "Grey"] }],
  ["home-decor", "yemanuel-home", "Fitted Sheet 140cm Cotton", 349,
    { colors: ["White", "Beige"] }],
  ["home-decor", "yemanuel-home", "Lightweight Duvet Double", 799,
    { v: [{ n: "Double", o: { Size: "Double" }, d: 0 }] }],
  ["home-decor", "yemanuel-home", "Memory Foam Pillow Single", 249,
    { v: [{ n: "Single", o: { Size: "Single" }, d: 0 }] }],
  ["home-decor", "yemanuel-home", "Feather Pillow Pair", 349,
    { v: [{ n: "Pair", o: {} , d: 0 }] }],
  ["mattresses", "yemanuel-home", "Waterproof Mattress Protector Queen", 399,
    { v: [{ n: "Queen", o: { Size: "Queen" }, d: 0 }] }],
  ["home-decor", "yemanuel-home", "Fleece Throw Blanket 150x200cm", 249,
    { colors: ["Grey", "Burgundy"] }],
  ["home-decor", "yemanuel-home", "Kente Pattern Throw Blanket", 399,
    { colors: ["Multi"] }],
  ["home-decor", "yemanuel-home", "Cotton Pillowcase Set 2-Pack", 99,
    { colors: ["White", "Grey"] }],

  // ============ Bathroom ============
  ["home-decor", "yemanuel-home", "Bath Towel Set 3-Piece Cotton", 299,
    { colors: ["White", "Grey", "Blue"] }],
  ["home-decor", "yemanuel-home", "Microfibre Bath Towel XL", 199,
    { colors: ["Teal", "Grey"] }],
  ["home-decor", "yemanuel-home", "Non-Slip Bath Mat", 149,
    { colors: ["Grey", "Beige"] }],
  ["home-decor", "yemanuel-home", "Waterproof Shower Curtain", 199,
    { colors: ["White", "Blue"] }],
  ["home-decor", "yemanuel-home", "Bathroom Accessory Set 5-Piece", 499,
    { v: [{ n: "5-Piece", o: { Pack: "5" }, d: 0 }] }],
  ["home-decor", "yemanuel-home", "Stainless Steel Toilet Roll Holder", 129,
    { colors: ["Steel"] }],

  // ============ Décor ============
  ["home-decor", "yemanuel-home", "Abstract Canvas Wall Art Set 3-Piece", 899,
    { colors: ["Gold", "Black"] }],
  ["home-decor", "yemanuel-home", "Ankara Fabric Wall Art Panel", 499,
    { colors: ["Multi"] }],
  ["home-decor", "yemanuel-home", "Ceramic Floor Vase 60cm", 599,
    { colors: ["White", "Terracotta"] }],
  ["home-decor", "yemanuel-home", "Scented Soy Candle Jar 200g", 199,
    { colors: ["Vanilla", "Lavender", "Sandalwood"] }],
  ["home-decor", "yemanuel-home", "Pillar Candle Set Ivory", 149,
    { colors: ["Ivory"] }],
  ["home-decor", "yemanuel-home", "Reed Diffuser 120ml", 249,
    { colors: ["Sea Breeze", "Oud"] }],
  ["home-decor", "yemanuel-home", "Beaded Decorative Bowl", 249,
    { colors: ["Multi"] }],
  ["home-decor", "yemanuel-home", "Picture Frame Set of 4 Collage", 299,
    { colors: ["Black", "Walnut"] }],
  ["home-decor", "yemanuel-home", "Resin Animal Figurine", 199,
    { colors: ["Bronze"] }],
  ["home-decor", "yemanuel-home", "Woven Wall Hanging", 349,
    { colors: ["Natural", "Black"] }],
  ["home-decor", "yemanuel-home", "Wall Clock 40cm Silent", 349,
    { colors: ["Black", "Gold"] }],
  ["home-decor", "yemanuel-home", "LED Strip Lights 5m", 149,
    { colors: ["RGB"] }],

  // ============ Lighting ============
  ["home-decor", "philips", "Philips LED Bulb 9W E27 Pack of 4", 149,
    { v: [{ n: "4-Pack", o: { Pack: "4" }, d: 0 }] }],
  ["home-decor", "philips", "Philips LED Tube 18W", 129,
    { v: [{ n: "18W", o: {} , d: 0 }] }],
  ["home-decor", "yemanuel-home", "Modern Ceiling Light Pendant", 899,
    { colors: ["Black", "Gold"] }],
  ["home-decor", "philips", "Philips LED Filament Bulb 6W", 59,
    { v: [{ n: "6W", o: {} , d: 0 }] }],
  ["home-decor", "yemanuel-home", "LED Desk Lamp USB Rechargeable", 299,
    { colors: ["White", "Black"] }],
  ["home-decor", "yemanuel-home", "Floor Lamp with Fabric Shade", 1299,
    { colors: ["Beige"] }],
  ["home-decor", "yemanuel-home", "Bedside Table Lamp Set of 2", 799,
    { colors: ["White", "Grey"] }],
  ["home-decor", "yemanuel-home", "Fairy String Lights 10m", 149,
    { colors: ["Warm White"] }],

  // ============ Storage & Organisation ============
  ["storage-containers", "yemanuel-home", "Storage Box Set of 6 Stackable", 599,
    { colors: ["Grey", "Beige"] }],
  ["shelving", "yemanuel-home", "Wall Shelf 60cm Floating", 349,
    { colors: ["Walnut", "Black"] }],
  ["storage-containers", "yemanuel-home", "Clothes Organizer Cubes Set 4-Pack", 349,
    { colors: ["Black", "Grey"] }],
  ["storage-containers", "yemanuel-home", "Hanging Shoe Organizer 24-Pocket", 249,
    { colors: ["Black"] }],

  // ============ Cleaning ============
  ["cleaning-supplies", "scotch-brite", "Scotch-Brite Scourer Pads 3-Pack", 39,
    { v: [{ n: "3-Pack", o: { Pack: "3" }, d: 0 }] }],
  ["brooms-brushes", "yemanuel-home", "Spin Mop with Bucket", 399,
    { colors: ["Blue", "Grey"] }],
  ["brooms-brushes", "yemanuel-home", "Broom & Dustpan Set", 149,
    { colors: ["Multi"] }],
  ["cleaning-supplies", "royal", "Vacuum Cleaner Filter Pack", 129,
    { v: [{ n: "Pack", o: {} , d: 0 }] }],
  ["cleaning-supplies", "yemanuel-home", "Microfibre Cleaning Cloth 10-Pack", 99,
    { colors: ["Multi"] }],
  ["bins", "yemanuel-home", "Pedal Bin 15L", 499,
    { colors: ["Silver"] }],
  ["laundry", "omo", "OMO Washing Powder 2kg", 149,
    { v: [{ n: "2kg", o: { Size: "2kg" }, d: 0 }] }],
  ["laundry", "omo", "OMO Liquid Detergent 3L", 249,
    { v: [{ n: "3L", o: { Size: "3L" }, d: 0 }] }],

  // ============ Home Office ============

  // ============ Pets ============

  // ============ Plants & Garden ============

  // ============ Home Improvement ============

  // ============ Laundry ============
  ["laundry", "yemanuel-home", "Retractable Clothesline 10m", 199,
    { v: [{ n: "10m", o: { Length: "10m" }, d: 0 }] }],
  ["laundry", "yemanuel-home", "Woven Laundry Basket", 299,
    { colors: ["Natural", "Grey"] }],
  ["laundry", "yemanuel-home", "Ironing Board with Pad Cover", 449,
    { v: [{ n: "Standard", o: {} , d: 0 }] }],
  ["laundry", "yemanuel-home", "Portable Clothes Rack 120cm", 799,
    { colors: ["Black", "Walnut"] }],
  ["laundry", "omo", "OMO Ultra Powder 500g", 49,
    { v: [{ n: "500g", o: { Size: "500g" }, d: 0 }] }],

  // ============ Umbrella fills ============
];